-- Auto-generated from lib/universities.ts
-- 159 bachelor programs
-- Generated: 2026-04-04T13:00:50.384Z

DELETE FROM universities WHERE level = 'bachelor';

INSERT INTO universities
  (id, name, country, country_code, city, program, department, level,
   required_gpa, required_language, required_language_score, accepted_languages,
   tuition_eur, flag, deadline, rankings, acceptance_rate, competitiveness,
   data_verified, program_restricted, lat, lng, image_url, duration_years,
   country_color, website)
VALUES
  ('tu-delft-bsc-ae', 'TU Delft', 'Hollanda', 'NL',
   'Delft', 'BSc Aerospace Engineering', 'Havacılık Mühendisliği', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   13536, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":15,"year":2025}]'::jsonb, 60, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('tu-delft-bsc-cs', 'TU Delft', 'Hollanda', 'NL',
   'Delft', 'BSc Computer Science & Engineering', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   13536, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":15,"year":2025}]'::jsonb, 50, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('amsterdam-bsc-economics', 'University of Amsterdam', 'Hollanda', 'NL',
   'Amsterdam', 'BSc Economics & Business Economics', 'Ekonomi', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   12150, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":25,"year":2025}]'::jsonb, 65, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('amsterdam-bsc-cs', 'University of Amsterdam', 'Hollanda', 'NL',
   'Amsterdam', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   12150, '🇳🇱', '1 Mayıs', '[{"source":"QS Europe","rank":25,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('groningen-bsc-psychology', 'University of Groningen', 'Hollanda', 'NL',
   'Groningen', 'BSc Psychology', 'Psikoloji', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   11500, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":45,"year":2025}]'::jsonb, 55, 'medium',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('groningen-bsc-ir', 'University of Groningen', 'Hollanda', 'NL',
   'Groningen', 'BSc International Relations & International Organization', 'Uluslararası İlişkiler', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   11500, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":45,"year":2025}]'::jsonb, 65, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('maastricht-bsc-business', 'Maastricht University', 'Hollanda', 'NL',
   'Maastricht', 'BSc International Business', 'İşletme', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   11000, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":60,"year":2025}]'::jsonb, 55, 'medium',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('eindhoven-bsc-me', 'TU Eindhoven', 'Hollanda', 'NL',
   'Eindhoven', 'BSc Mechanical Engineering', 'Makine Mühendisliği', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   13400, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":35,"year":2025}]'::jsonb, 60, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('bocconi-bsc-economics', 'Bocconi University', 'İtalya', 'IT',
   'Milano', 'BSc International Economics, Management & Finance', 'Ekonomi', 'bachelor',
   80, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"85"}]'::jsonb,
   14000, '🇮🇹', 'Ocak (Early), Nisan (Regular)', '[{"source":"QS Europe","rank":16,"year":2025}]'::jsonb, 15, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('bocconi-bsc-business', 'Bocconi University', 'İtalya', 'IT',
   'Milano', 'BSc International Economics & Management', 'İşletme', 'bachelor',
   80, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"85"}]'::jsonb,
   14000, '🇮🇹', 'Ocak (Early), Nisan (Regular)', '[{"source":"QS Europe","rank":16,"year":2025}]'::jsonb, 18, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('polimi-bsc-eng', 'Politecnico di Milano', 'İtalya', 'IT',
   'Milano', 'BSc Engineering (TOL test required)', 'Mühendislik', 'bachelor',
   70, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"70"}]'::jsonb,
   3900, '🇮🇹', 'Temmuz', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 55, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('bologna-bsc-business', 'University of Bologna', 'İtalya', 'IT',
   'Bologna', 'BSc Business & Economics (CLABE)', 'Ekonomi', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"70"}]'::jsonb,
   2900, '🇮🇹', 'Mayıs', '[{"source":"QS Europe","rank":48,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('tum-bsc-management', 'TU München', 'Almanya', 'DE',
   'Münih', 'BSc Management & Technology', 'İşletme', 'bachelor',
   80, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   0, '🇩🇪', '15 Temmuz', '[{"source":"QS Europe","rank":19,"year":2025}]'::jsonb, 25, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('rwth-bsc-business', 'RWTH Aachen', 'Almanya', 'DE',
   'Aachen', 'BSc Business Administration (English track)', 'İşletme', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   0, '🇩🇪', '15 Temmuz', '[{"source":"QS Europe","rank":33,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('jacobs-bsc-cs', 'Jacobs University Bremen', 'Almanya', 'DE',
   'Bremen', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   20000, '🇩🇪', '1 Haziran', NULL, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ucl-bsc-economics', 'UCL (University College London)', 'İngiltere', 'GB',
   'Londra', 'BSc Economics', 'Ekonomi', 'bachelor',
   85, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   30000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":4,"year":2025}]'::jsonb, 12, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('imperial-bsc-cs', 'Imperial College London', 'İngiltere', 'GB',
   'Londra', 'BEng Computing', 'Bilgisayar Mühendisliği', 'bachelor',
   90, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   38000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":3,"year":2025}]'::jsonb, 8, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('edinburgh-bsc-cs', 'University of Edinburgh', 'İngiltere', 'GB',
   'Edinburgh', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   82, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   28000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":12,"year":2025}]'::jsonb, 18, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('warwick-bsc-economics', 'University of Warwick', 'İngiltere', 'GB',
   'Coventry', 'BSc Economics', 'Ekonomi', 'bachelor',
   85, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   28000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":22,"year":2025}]'::jsonb, 15, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('manchester-bsc-business', 'University of Manchester', 'İngiltere', 'GB',
   'Manchester', 'BSc International Business, Finance & Economics', 'İşletme', 'bachelor',
   80, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   27500, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":14,"year":2025}]'::jsonb, 22, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('kcl-bsc-business', 'King''s College London', 'İngiltere', 'GB',
   'Londra', 'BSc Business Management', 'İşletme', 'bachelor',
   82, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   28000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":11,"year":2025}]'::jsonb, 18, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('lund-bsc-economics', 'Lund University', 'İsveç', 'SE',
   'Lund', 'BSc International Business', 'İşletme', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   10000, '🇸🇪', '15 Ocak', '[{"source":"QS Europe","rank":28,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('cbs-bsc-business', 'Copenhagen Business School', 'Danimarka', 'DK',
   'Kopenhag', 'BSc International Business', 'İşletme', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"91"}]'::jsonb,
   12500, '🇩🇰', '15 Mart', '[{"source":"QS Europe","rank":53,"year":2025}]'::jsonb, 30, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ie-bsc-business', 'IE University', 'İspanya', 'ES',
   'Madrid', 'Bachelor in Business Administration', 'İşletme', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   23900, '🇪🇸', 'Rolling (erken başvuru önerilir)', '[{"source":"QS Europe","rank":80,"year":2025}]'::jsonb, 25, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ie-bsc-cs', 'IE University', 'İspanya', 'ES',
   'Madrid', 'Bachelor in Computer Science & AI', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   23900, '🇪🇸', 'Rolling (erken başvuru önerilir)', '[{"source":"QS Europe","rank":80,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('trinity-bsc-business', 'Trinity College Dublin', 'İrlanda', 'IE',
   'Dublin', 'BSc Business Studies', 'İşletme', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   20700, '🇮🇪', '1 Şubat', '[{"source":"QS Europe","rank":42,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('trinity-bsc-cs', 'Trinity College Dublin', 'İrlanda', 'IE',
   'Dublin', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   23640, '🇮🇪', '1 Şubat', '[{"source":"QS Europe","rank":42,"year":2025}]'::jsonb, 25, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('charles-bsc-economics', 'Charles University Prague', 'Çekya', 'CZ',
   'Prag', 'BSc Economics & Finance', 'Ekonomi', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   6000, '🇨🇿', '30 Nisan', '[{"source":"QS Europe","rank":75,"year":2025}]'::jsonb, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('corvinus-bsc-business', 'Corvinus University of Budapest', 'Macaristan', 'HU',
   'Budapeşte', 'BSc International Business', 'İşletme', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   4800, '🇭🇺', '2 Şubat', '[{"source":"QS Europe","rank":120,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('kozminski-bsc-management', 'Kozminski University', 'Polonya', 'PL',
   'Varşova', 'BSc Management', 'İşletme', 'bachelor',
   60, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   4900, '🇵🇱', '15 Temmuz', NULL, 65, 'low',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('erasmus-bsc-economics', 'Erasmus University Rotterdam', 'Hollanda', 'NL',
   'Rotterdam', 'BSc Economics & Business Economics', 'Ekonomi', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   12100, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":32,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('erasmus-bsc-iba', 'Erasmus University Rotterdam', 'Hollanda', 'NL',
   'Rotterdam', 'BSc International Business Administration', 'İşletme', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   12100, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":32,"year":2025}]'::jsonb, 50, 'medium',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('utrecht-bsc-economics', 'Utrecht University', 'Hollanda', 'NL',
   'Utrecht', 'BSc Economics & Business Economics', 'Ekonomi', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   12500, '🇳🇱', '1 Mayıs', '[{"source":"QS Europe","rank":20,"year":2025}]'::jsonb, 60, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('utrecht-bsc-las', 'Utrecht University', 'Hollanda', 'NL',
   'Utrecht', 'BSc Liberal Arts & Sciences', 'Liberal Sanatlar', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   12500, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":20,"year":2025}]'::jsonb, 50, 'medium',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('leiden-bsc-polsci', 'Leiden University', 'Hollanda', 'NL',
   'Leiden', 'BSc Political Science', 'Siyaset Bilimi', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   12500, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('leiden-bsc-ir', 'Leiden University', 'Hollanda', 'NL',
   'Leiden', 'BSc International Relations & Organisations', 'Uluslararası İlişkiler', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   12500, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('vu-bsc-ba', 'Vrije Universiteit Amsterdam', 'Hollanda', 'NL',
   'Amsterdam', 'BSc Business Analytics', 'İş Analitiği', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   12560, '🇳🇱', '1 Nisan', '[{"source":"QS Europe","rank":55,"year":2025}]'::jsonb, 50, 'medium',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('vu-bsc-ib', 'Vrije Universiteit Amsterdam', 'Hollanda', 'NL',
   'Amsterdam', 'BSc International Business Administration', 'İşletme', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   12560, '🇳🇱', '1 Nisan', '[{"source":"QS Europe","rank":55,"year":2025}]'::jsonb, 60, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('tilburg-bsc-iba', 'Tilburg University', 'Hollanda', 'NL',
   'Tilburg', 'BSc International Business Administration', 'İşletme', 'bachelor',
   68, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   10700, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":65,"year":2025}]'::jsonb, 65, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('tilburg-bsc-economics', 'Tilburg University', 'Hollanda', 'NL',
   'Tilburg', 'BSc Economics', 'Ekonomi', 'bachelor',
   68, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   10700, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":65,"year":2025}]'::jsonb, 65, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('wageningen-bsc-food', 'Wageningen University', 'Hollanda', 'NL',
   'Wageningen', 'BSc Food Technology', 'Gıda Teknolojisi', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   13400, '🇳🇱', '1 Mayıs', '[{"source":"QS Europe","rank":40,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('radboud-bsc-ba', 'Radboud University', 'Hollanda', 'NL',
   'Nijmegen', 'BSc Business Administration', 'İşletme', 'bachelor',
   68, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   11700, '🇳🇱', '1 Nisan', '[{"source":"QS Europe","rank":58,"year":2025}]'::jsonb, 60, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('twente-bsc-tcs', 'University of Twente', 'Hollanda', 'NL',
   'Enschede', 'BSc Technical Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   13750, '🇳🇱', '30 Nisan', '[{"source":"QS Europe","rank":70,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('twente-bsc-iba', 'University of Twente', 'Hollanda', 'NL',
   'Enschede', 'BSc International Business Administration', 'İşletme', 'bachelor',
   68, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   12750, '🇳🇱', '1 Mayıs', '[{"source":"QS Europe","rank":70,"year":2025}]'::jsonb, 60, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('padua-bsc-economics', 'University of Padua', 'İtalya', 'IT',
   'Padova', 'BSc Economics', 'Ekonomi', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2800, '🇮🇹', 'Mart', '[{"source":"QS Europe","rank":55,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('trento-bsc-economics', 'University of Trento', 'İtalya', 'IT',
   'Trento', 'BSc Economics & Management', 'Ekonomi', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2500, '🇮🇹', 'Mart', '[{"source":"QS Europe","rank":90,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('luiss-bsc-economics', 'LUISS Guido Carli', 'İtalya', 'IT',
   'Roma', 'BSc Economics & Business', 'Ekonomi', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   12000, '🇮🇹', 'Mart', '[{"source":"QS Europe","rank":110,"year":2025}]'::jsonb, 35, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('luiss-bsc-polsci', 'LUISS Guido Carli', 'İtalya', 'IT',
   'Roma', 'BSc Political Science', 'Siyaset Bilimi', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   12000, '🇮🇹', 'Mart', '[{"source":"QS Europe","rank":110,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('milan-bsc-intpol', 'University of Milan', 'İtalya', 'IT',
   'Milano', 'BSc International Politics, Law & Economics', 'Siyaset Bilimi', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   3000, '🇮🇹', 'Haziran', '[{"source":"QS Europe","rank":52,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('cafoscari-bsc-dm', 'Ca'' Foscari University of Venice', 'İtalya', 'IT',
   'Venedik', 'BSc Digital Management', 'Dijital Yönetim', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2800, '🇮🇹', 'Nisan', '[{"source":"QS Europe","rank":100,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('constructor-bsc-iba', 'Constructor University Bremen', 'Almanya', 'DE',
   'Bremen', 'BSc International Business Administration', 'İşletme', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   20000, '🇩🇪', '1 Haziran', NULL, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('constructor-bsc-datasci', 'Constructor University Bremen', 'Almanya', 'DE',
   'Bremen', 'BSc Data Science', 'Veri Bilimi', 'bachelor',
   72, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   20000, '🇩🇪', '1 Haziran', NULL, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('escp-bsc-management', 'ESCP Business School', 'Almanya', 'DE',
   'Berlin', 'BSc in Management', 'İşletme', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   17900, '🇩🇪', 'Haziran (rolling)', '[{"source":"QS Europe","rank":85,"year":2025}]'::jsonb, 30, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('bard-ba-humanities', 'Bard College Berlin', 'Almanya', 'DE',
   'Berlin', 'BA Humanities, Arts & Social Thought', 'Liberal Sanatlar', 'bachelor',
   72, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   19500, '🇩🇪', '1 Mayıs', NULL, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('whu-bsc-iba', 'WHU – Otto Beisheim School of Management', 'Almanya', 'DE',
   'Vallendar', 'BSc International Business Administration', 'İşletme', 'bachelor',
   80, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"95"}]'::jsonb,
   9990, '🇩🇪', '15 Mayıs', '[{"source":"QS Europe","rank":95,"year":2025}]'::jsonb, 25, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ebs-bsc-business', 'EBS Universität', 'Almanya', 'DE',
   'Wiesbaden', 'BSc Business Studies', 'İşletme', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   9480, '🇩🇪', 'Rolling', NULL, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('bristol-bsc-economics', 'University of Bristol', 'İngiltere', 'GB',
   'Bristol', 'BSc Economics', 'Ekonomi', 'bachelor',
   80, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   25000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":18,"year":2025}]'::jsonb, 18, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('leeds-bsc-business', 'University of Leeds', 'İngiltere', 'GB',
   'Leeds', 'BSc Business Management', 'İşletme', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   26500, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":35,"year":2025}]'::jsonb, 22, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('birmingham-bsc-business', 'University of Birmingham', 'İngiltere', 'GB',
   'Birmingham', 'BSc Business Management', 'İşletme', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   24000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 20, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('bath-bsc-ba', 'University of Bath', 'İngiltere', 'GB',
   'Bath', 'BSc Business Administration', 'İşletme', 'bachelor',
   80, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   22000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 15, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('loughborough-bsc-be', 'Loughborough University', 'İngiltere', 'GB',
   'Loughborough', 'BSc Business Economics', 'Ekonomi', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   21000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":60,"year":2025}]'::jsonb, 28, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('glasgow-bsc-cs', 'University of Glasgow', 'İngiltere', 'GB',
   'Glasgow', 'BSc Computing Science', 'Bilgisayar Mühendisliği', 'bachelor',
   80, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   27500, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":26,"year":2025}]'::jsonb, 20, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('lse-bsc-economics', 'London School of Economics (LSE)', 'İngiltere', 'GB',
   'Londra', 'BSc Economics', 'Ekonomi', 'bachelor',
   90, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"107"}]'::jsonb,
   32000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":6,"year":2025}]'::jsonb, 8, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('oxford-ba-em', 'University of Oxford', 'İngiltere', 'GB',
   'Oxford', 'BA Economics & Management', 'Ekonomi', 'bachelor',
   92, 'IELTS', '7.5', '[{"test":"IELTS","minScore":"7.5"},{"test":"TOEFL","minScore":"110"}]'::jsonb,
   38000, '🇬🇧', '15 Ekim (UCAS erken)', '[{"source":"QS Europe","rank":1,"year":2025}]'::jsonb, 5, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('cambridge-ba-economics', 'University of Cambridge', 'İngiltere', 'GB',
   'Cambridge', 'BA Economics', 'Ekonomi', 'bachelor',
   92, 'IELTS', '7.5', '[{"test":"IELTS","minScore":"7.5"},{"test":"TOEFL","minScore":"110"}]'::jsonb,
   37000, '🇬🇧', '15 Ekim (UCAS erken)', '[{"source":"QS Europe","rank":2,"year":2025}]'::jsonb, 6, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('stockholm-bsc-be', 'Stockholm University', 'İsveç', 'SE',
   'Stockholm', 'BSc Business & Economics', 'Ekonomi', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   11000, '🇸🇪', '15 Ocak', '[{"source":"QS Europe","rank":45,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('uppsala-bsc-be', 'Uppsala University', 'İsveç', 'SE',
   'Uppsala', 'BSc Business & Economics', 'Ekonomi', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   10500, '🇸🇪', '15 Ocak', '[{"source":"QS Europe","rank":38,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('aarhus-bsc-ba', 'Aarhus University', 'Danimarka', 'DK',
   'Aarhus', 'BSc Business Administration', 'İşletme', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   13500, '🇩🇰', '15 Mart', '[{"source":"QS Europe","rank":42,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sdu-bsc-eng', 'University of Southern Denmark', 'Danimarka', 'DK',
   'Odense', 'BSc Engineering (Electronics)', 'Mühendislik', 'bachelor',
   68, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   13000, '🇩🇰', '15 Mart', '[{"source":"QS Europe","rank":80,"year":2025}]'::jsonb, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('aalto-bsc-ib', 'Aalto University', 'Finlandiya', 'FI',
   'Helsinki', 'BSc International Business', 'İşletme', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   15000, '🇫🇮', '22 Ocak', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 20, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('helsinki-bsc-science', 'University of Helsinki', 'Finlandiya', 'FI',
   'Helsinki', 'BSc Science (English track)', 'Fen Bilimleri', 'bachelor',
   72, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   15000, '🇫🇮', '16 Ocak', '[{"source":"QS Europe","rank":35,"year":2025}]'::jsonb, 25, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('esade-bba', 'ESADE Business School', 'İspanya', 'ES',
   'Barselona', 'Bachelor in Business Administration (BBA)', 'İşletme', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   18200, '🇪🇸', 'Rolling (erken başvuru önerilir)', '[{"source":"QS Europe","rank":75,"year":2025}]'::jsonb, 25, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ub-bsc-business', 'University of Barcelona', 'İspanya', 'ES',
   'Barselona', 'BSc International Business (English)', 'İşletme', 'bachelor',
   65, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   5500, '🇪🇸', 'Haziran', '[{"source":"QS Europe","rank":48,"year":2025}]'::jsonb, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('modul-bsc-im', 'Modul University Vienna', 'Avusturya', 'AT',
   'Viyana', 'BSc International Management', 'İşletme', 'bachelor',
   68, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   13900, '🇦🇹', 'Rolling', NULL, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('wu-bsc-be', 'WU Vienna University of Economics and Business', 'Avusturya', 'AT',
   'Viyana', 'BSc Business & Economics (English track)', 'Ekonomi', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   1500, '🇦🇹', '19 Mayıs', '[{"source":"QS Europe","rank":55,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('kuleuven-bsc-beng', 'KU Leuven', 'Belçika', 'BE',
   'Leuven', 'BSc Business Engineering (English)', 'İşletme Mühendisliği', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   6000, '🇧🇪', '1 Mart', '[{"source":"QS Europe","rank":24,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ghent-bsc-beng', 'Ghent University', 'Belçika', 'BE',
   'Gent', 'BSc Business Engineering', 'İşletme Mühendisliği', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   5300, '🇧🇪', '1 Mart', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('nova-bsc-economics', 'Nova School of Business & Economics', 'Portekiz', 'PT',
   'Lizbon', 'BSc Economics', 'Ekonomi', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   7500, '🇵🇹', 'Haziran', '[{"source":"QS Europe","rank":70,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('nova-bsc-management', 'Nova School of Business & Economics', 'Portekiz', 'PT',
   'Lizbon', 'BSc Management', 'İşletme', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   7500, '🇵🇹', 'Haziran', '[{"source":"QS Europe","rank":70,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('catolica-bsc-management', 'Católica Lisbon School of Business & Economics', 'Portekiz', 'PT',
   'Lizbon', 'BSc Management', 'İşletme', 'bachelor',
   72, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   6800, '🇵🇹', 'Haziran', '[{"source":"QS Europe","rank":85,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ucd-bsc-business', 'University College Dublin (UCD)', 'İrlanda', 'IE',
   'Dublin', 'BSc Business', 'İşletme', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   19400, '🇮🇪', '1 Şubat', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ucd-bsc-cs', 'University College Dublin (UCD)', 'İrlanda', 'IE',
   'Dublin', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   22900, '🇮🇪', '1 Şubat', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ucc-bsc-bis', 'University College Cork', 'İrlanda', 'IE',
   'Cork', 'BSc Business Information Systems', 'Bilgi Sistemleri', 'bachelor',
   68, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   17000, '🇮🇪', '31 Mayıs', '[{"source":"QS Europe","rank":75,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('erasmus-bsc-econometrics', 'Erasmus University Rotterdam', 'Hollanda', 'NL',
   'Rotterdam', 'BSc Econometrics & Operations Research', 'Ekonometri', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   12100, '🇳🇱', '1 Nisan', '[{"source":"QS Europe","rank":32,"year":2025}]'::jsonb, 45, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('groningen-bsc-economics', 'University of Groningen', 'Hollanda', 'NL',
   'Groningen', 'BSc Economics & Business Economics', 'Ekonomi', 'bachelor',
   68, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   11500, '🇳🇱', '1 Mayıs', '[{"source":"QS Europe","rank":45,"year":2025}]'::jsonb, 60, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('maastricht-bsc-economics', 'Maastricht University', 'Hollanda', 'NL',
   'Maastricht', 'BSc Econometrics & Operations Research', 'Ekonometri', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   11000, '🇳🇱', '1 Nisan', '[{"source":"QS Europe","rank":60,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('leiden-bsc-psychology', 'Leiden University', 'Hollanda', 'NL',
   'Leiden', 'BSc Psychology (English)', 'Psikoloji', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   12500, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 50, 'medium',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('bologna-bsc-polsci', 'University of Bologna', 'İtalya', 'IT',
   'Bologna', 'BSc Diplomatic & International Sciences', 'Uluslararası İlişkiler', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2900, '🇮🇹', 'Mayıs', '[{"source":"QS Europe","rank":48,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('torino-bsc-business', 'University of Turin', 'İtalya', 'IT',
   'Torino', 'BSc Business & Management (English)', 'İşletme', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2700, '🇮🇹', 'Temmuz', '[{"source":"QS Europe","rank":80,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('polimi-bsc-design', 'Politecnico di Milano', 'İtalya', 'IT',
   'Milano', 'BSc Design (English track)', 'Tasarım', 'bachelor',
   70, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"70"}]'::jsonb,
   3900, '🇮🇹', 'Temmuz', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 45, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('constructor-bsc-biochem', 'Constructor University Bremen', 'Almanya', 'DE',
   'Bremen', 'BSc Biochemistry & Cell Biology', 'Biyokimya', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   20000, '🇩🇪', '1 Haziran', NULL, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('tum-bsc-cs', 'TU München', 'Almanya', 'DE',
   'Münih', 'BSc Informatics (English track)', 'Bilgisayar Mühendisliği', 'bachelor',
   82, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   0, '🇩🇪', '15 Temmuz', '[{"source":"QS Europe","rank":19,"year":2025}]'::jsonb, 20, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('exeter-bsc-business', 'University of Exeter', 'İngiltere', 'GB',
   'Exeter', 'BSc Business', 'İşletme', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   23000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":40,"year":2025}]'::jsonb, 20, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('nottingham-bsc-economics', 'University of Nottingham', 'İngiltere', 'GB',
   'Nottingham', 'BSc Economics', 'Ekonomi', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   24000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":32,"year":2025}]'::jsonb, 22, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sheffield-bsc-cs', 'University of Sheffield', 'İngiltere', 'GB',
   'Sheffield', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   76, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   26200, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":38,"year":2025}]'::jsonb, 25, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('southampton-bsc-cs', 'University of Southampton', 'İngiltere', 'GB',
   'Southampton', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   76, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   25000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":36,"year":2025}]'::jsonb, 24, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('aalto-bsc-datasci', 'Aalto University', 'Finlandiya', 'FI',
   'Helsinki', 'BSc Data Science', 'Veri Bilimi', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   15000, '🇫🇮', '22 Ocak', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 18, 'high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('kuleuven-bsc-economics', 'KU Leuven', 'Belçika', 'BE',
   'Leuven', 'BSc Economics (English)', 'Ekonomi', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   6000, '🇧🇪', '1 Mart', '[{"source":"QS Europe","rank":24,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('dtu-bsc-eng', 'Technical University of Denmark (DTU)', 'Danimarka', 'DK',
   'Kopenhag', 'BSc General Engineering (English)', 'Mühendislik', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   15000, '🇩🇰', '15 Mart', '[{"source":"QS Europe","rank":38,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('kth-bsc-eng', 'KTH Royal Institute of Technology', 'İsveç', 'SE',
   'Stockholm', 'BSc Information & Communication Technology', 'Bilişim Teknolojileri', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   16000, '🇸🇪', '15 Ocak', '[{"source":"QS Europe","rank":28,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sciences-po-bsc-polsci', 'Sciences Po', 'Fransa', 'FR',
   'Paris', 'Political Science (Bachelor)', 'Siyaset Bilimi', 'bachelor',
   85, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   0, '🇫🇷', '10 Mart', '[{"source":"QS Europe","rank":2,"year":2025}]'::jsonb, 12, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sciences-po-bsc-economics', 'Sciences Po', 'Fransa', 'FR',
   'Reims', 'Economics & Society (Bachelor)', 'Ekonomi', 'bachelor',
   83, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   0, '🇫🇷', '10 Mart', '[{"source":"QS Europe","rank":2,"year":2025}]'::jsonb, 15, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('lmu-bsc-economics', 'LMU München', 'Almanya', 'DE',
   'Münih', 'Economics (Bachelor)', 'Ekonomi', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"85"}]'::jsonb,
   140, '🇩🇪', '15 Temmuz', '[{"source":"QS Europe","rank":59,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('mannheim-bsc-business', 'University of Mannheim', 'Almanya', 'DE',
   'Mannheim', 'Business Administration (Bachelor)', 'İşletme', 'bachelor',
   80, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   1500, '🇩🇪', '31 Mayıs', '[{"source":"QS Europe","rank":25,"year":2025}]'::jsonb, 17, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('st-gallen-bsc-ia', 'University of St. Gallen', 'İsviçre', 'CH',
   'St. Gallen', 'International Affairs (Bachelor)', 'Uluslararası İlişkiler', 'bachelor',
   85, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   3460, '🇨🇭', 'Ocak (erken), Haziran (geç)', '[{"source":"QS Europe","rank":15,"year":2025}]'::jsonb, 20, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('karolinska-bsc-biomed', 'Karolinska Institute', 'İsveç', 'SE',
   'Stockholm', 'Biomedicine (Bachelor)', 'Tıp Bilimleri', 'bachelor',
   85, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   19000, '🇸🇪', '15 Ocak', '[{"source":"QS Europe","rank":7,"year":2025}]'::jsonb, 8, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('aalborg-bsc-electronics', 'Aalborg University', 'Danimarka', 'DK',
   'Aalborg', 'BSc Electronics & IT', 'Elektrik-Elektronik Mühendisliği', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   13300, '🇩🇰', '15 Mart', '[{"source":"QS Europe","rank":130,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('aalborg-bsc-energy', 'Aalborg University', 'Danimarka', 'DK',
   'Aalborg', 'BSc Energy Engineering', 'Mühendislik', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   13300, '🇩🇰', '15 Mart', '[{"source":"QS Europe","rank":130,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('antwerp-bsc-be', 'University of Antwerp', 'Belçika', 'BE',
   'Antwerp', 'BSc Business Engineering', 'İşletme', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   6000, '🇧🇪', '1 Mart', '[{"source":"QS Europe","rank":95,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('durham-bsc-cs', 'Durham University', 'İngiltere', 'GB',
   'Durham', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   82, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   29000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":25,"year":2025}]'::jsonb, 20, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('durham-bsc-economics', 'Durham University', 'İngiltere', 'GB',
   'Durham', 'BSc Economics', 'Ekonomi', 'bachelor',
   82, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   24500, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":25,"year":2025}]'::jsonb, 22, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('lancaster-bsc-business', 'Lancaster University', 'İngiltere', 'GB',
   'Lancaster', 'BSc Business Management', 'İşletme', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   24000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('lancaster-bsc-cs', 'Lancaster University', 'İngiltere', 'GB',
   'Lancaster', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   27000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('standrews-bsc-cs', 'University of St Andrews', 'İngiltere', 'GB',
   'St Andrews', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   85, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   28000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":18,"year":2025}]'::jsonb, 15, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('standrews-bsc-economics', 'University of St Andrews', 'İngiltere', 'GB',
   'St Andrews', 'BSc Economics', 'Ekonomi', 'bachelor',
   85, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   26000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":18,"year":2025}]'::jsonb, 12, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('standrews-bsc-ir', 'University of St Andrews', 'İngiltere', 'GB',
   'St Andrews', 'MA International Relations', 'Uluslararası İlişkiler', 'bachelor',
   85, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   26000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":18,"year":2025}]'::jsonb, 12, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('polito-bsc-eng', 'Politecnico di Torino', 'İtalya', 'IT',
   'Torino', 'BSc Engineering (English track)', 'Mühendislik', 'bachelor',
   70, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2800, '🇮🇹', 'Mayıs', '[{"source":"QS Europe","rank":55,"year":2025}]'::jsonb, 40, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('polito-bsc-auto', 'Politecnico di Torino', 'İtalya', 'IT',
   'Torino', 'BSc Automotive Engineering', 'Makine Mühendisliği', 'bachelor',
   70, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2800, '🇮🇹', 'Mayıs', '[{"source":"QS Europe","rank":55,"year":2025}]'::jsonb, 40, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('carlos-iii-bsc-economics', 'Universidad Carlos III de Madrid', 'İspanya', 'ES',
   'Madrid', 'BSc Economics (English track)', 'Ekonomi', 'bachelor',
   72, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   6500, '🇪🇸', '10 Nisan', '[{"source":"QS Europe","rank":70,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('carlos-iii-bsc-business', 'Universidad Carlos III de Madrid', 'İspanya', 'ES',
   'Madrid', 'BSc Business Administration (Bilingual)', 'İşletme', 'bachelor',
   72, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   6500, '🇪🇸', '10 Nisan', '[{"source":"QS Europe","rank":70,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('pompeu-fabra-bsc-economics', 'Universitat Pompeu Fabra', 'İspanya', 'ES',
   'Barcelona', 'BSc Economics (English track)', 'Ekonomi', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   6800, '🇪🇸', 'Haziran', '[{"source":"QS Europe","rank":45,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('gothenburg-bsc-se', 'University of Gothenburg', 'İsveç', 'SE',
   'Göteborg', 'BSc Software Engineering & Management', 'Bilgisayar Mühendisliği', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   11500, '🇸🇪', '15 Ocak', '[{"source":"QS Europe","rank":65,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sse-bsc-economics', 'Stockholm School of Economics', 'İsveç', 'SE',
   'Stockholm', 'BSc Business & Economics', 'Ekonomi', 'bachelor',
   82, 'IELTS', '7.0', '[{"test":"IELTS","minScore":"7.0"},{"test":"TOEFL","minScore":"100"}]'::jsonb,
   18000, '🇸🇪', '15 Ocak', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 10, 'very_high',
   true, true, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('iscte-bsc-management', 'ISCTE – University Institute of Lisbon', 'Portekiz', 'PT',
   'Lizbon', 'BSc Management (English track)', 'İşletme', 'bachelor',
   65, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   4500, '🇵🇹', 'Haziran', '[{"source":"QS Europe","rank":140,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sgh-bsc-ib', 'SGH Warsaw School of Economics', 'Polonya', 'PL',
   'Varşova', 'BSc International Business', 'İşletme', 'bachelor',
   65, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   3200, '🇵🇱', '15 Temmuz', '[{"source":"QS Europe","rank":160,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sgh-bsc-economics', 'SGH Warsaw School of Economics', 'Polonya', 'PL',
   'Varşova', 'BSc Quantitative Economics', 'Ekonomi', 'bachelor',
   65, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   3200, '🇵🇱', '15 Temmuz', '[{"source":"QS Europe","rank":160,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('copenhagen-bsc-economics', 'University of Copenhagen', 'Danimarka', 'DK',
   'Kopenhag', 'BSc Economics', 'Ekonomi', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   12000, '🇩🇰', '15 Mart', '[{"source":"QS Europe","rank":17,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('essec-bba', 'ESSEC Business School', 'Fransa', 'FR',
   'Cergy (Paris)', 'BBA (Bachelor in Business Administration)', 'İşletme', 'bachelor',
   80, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"},{"test":"DELF/DALF","minScore":"B2"}]'::jsonb,
   17600, '🇫🇷', 'Rolling', '[{"source":"QS Europe","rank":12,"year":2025}]'::jsonb, 20, 'very_high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('edhec-bba', 'EDHEC Business School', 'Fransa', 'FR',
   'Nice', 'BBA (Bachelor in Business Administration)', 'İşletme', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"},{"test":"DELF/DALF","minScore":"B2"}]'::jsonb,
   14500, '🇫🇷', 'Mart', '[{"source":"QS Europe","rank":15,"year":2025}]'::jsonb, 25, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('skema-bba', 'SKEMA Business School', 'Fransa', 'FR',
   'Sophia Antipolis', 'Global BBA', 'İşletme', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"},{"test":"DELF/DALF","minScore":"B2"}]'::jsonb,
   12900, '🇫🇷', '15 Mayıs', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('emlyon-bba', 'emlyon business school', 'Fransa', 'FR',
   'Lyon', 'Global BBA', 'İşletme', 'bachelor',
   72, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"},{"test":"DELF/DALF","minScore":"B2"}]'::jsonb,
   15500, '🇫🇷', 'Mart', '[{"source":"QS Europe","rank":20,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('ieseg-bba', 'IESEG School of Management', 'Fransa', 'FR',
   'Lille', 'Bachelor in International Business', 'İşletme', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"},{"test":"DELF/DALF","minScore":"B2"}]'::jsonb,
   11950, '🇫🇷', '1 Haziran', '[{"source":"QS Europe","rank":33,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('neoma-bba', 'NEOMA Business School', 'Fransa', 'FR',
   'Reims', 'Global BBA', 'İşletme', 'bachelor',
   68, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"},{"test":"DELF/DALF","minScore":"B2"}]'::jsonb,
   12800, '🇫🇷', 'Haziran', '[{"source":"QS Europe","rank":40,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('kedge-bba', 'KEDGE Business School', 'Fransa', 'FR',
   'Marsilya', 'International BBA', 'İşletme', 'bachelor',
   65, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"},{"test":"DELF/DALF","minScore":"B2"}]'::jsonb,
   11500, '🇫🇷', 'Nisan', '[{"source":"QS Europe","rank":45,"year":2025}]'::jsonb, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('audencia-bba', 'Audencia Business School', 'Fransa', 'FR',
   'Nantes', 'Bachelor in Management', 'İşletme', 'bachelor',
   68, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"},{"test":"DELF/DALF","minScore":"B2"}]'::jsonb,
   11200, '🇫🇷', 'Haziran', '[{"source":"QS Europe","rank":38,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('tampere-bsc-tech', 'Tampere University', 'Finlandiya', 'FI',
   'Tampere', 'BSc Science & Engineering', 'Mühendislik', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   10000, '🇫🇮', '21 Ocak', '[{"source":"QS Europe","rank":85,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('turku-bsc-tech', 'University of Turku', 'Finlandiya', 'FI',
   'Turku', 'BSc Information & Communication Technology', 'Bilgisayar Mühendisliği', 'bachelor',
   68, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   10000, '🇫🇮', '21 Ocak', '[{"source":"QS Europe","rank":100,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('linkoping-bsc-se', 'Linköping University', 'İsveç', 'SE',
   'Linköping', 'BSc Software Engineering', 'Bilgisayar Mühendisliği', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   11500, '🇸🇪', '15 Ocak', '[{"source":"QS Europe","rank":75,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('bi-norwegian-bba', 'BI Norwegian Business School', 'Norveç', 'NO',
   'Oslo', 'Bachelor in Business Administration', 'İşletme', 'bachelor',
   72, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   9500, '🇳🇴', '1 Mart', '[{"source":"QS Europe","rank":55,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('nhh-bba', 'NHH Norwegian School of Economics', 'Norveç', 'NO',
   'Bergen', 'Bachelor in Economics & Business Administration', 'Ekonomi', 'bachelor',
   75, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   0, '🇳🇴', '15 Kasım', '[{"source":"QS Europe","rank":50,"year":2025}]'::jsonb, 25, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('queen-mary-bsc-economics', 'Queen Mary University of London', 'İngiltere', 'GB',
   'Londra', 'BSc Economics', 'Ekonomi', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"92"}]'::jsonb,
   22000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":40,"year":2025}]'::jsonb, 25, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('york-bsc-cs', 'University of York', 'İngiltere', 'GB',
   'York', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"87"}]'::jsonb,
   25000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":35,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('liverpool-bsc-business', 'University of Liverpool', 'İngiltere', 'GB',
   'Liverpool', 'BSc Business Management', 'İşletme', 'bachelor',
   72, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   21000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":42,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sussex-bsc-economics', 'University of Sussex', 'İngiltere', 'GB',
   'Brighton', 'BSc Economics', 'Ekonomi', 'bachelor',
   70, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"88"}]'::jsonb,
   20500, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":48,"year":2025}]'::jsonb, 35, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('sapienza-bsc-economics', 'Sapienza Università di Roma', 'İtalya', 'IT',
   'Roma', 'BSc Economics (English track)', 'Ekonomi', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2800, '🇮🇹', 'Mayıs', '[{"source":"QS Europe","rank":42,"year":2025}]'::jsonb, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('pavia-bsc-eng', 'University of Pavia', 'İtalya', 'IT',
   'Pavia', 'BSc Bioengineering (English)', 'Mühendislik', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   2500, '🇮🇹', 'Rolling (erken başvuru önerilir)', '[{"source":"QS Europe","rank":90,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('tu-berlin-bsc-cs', 'Technische Universität Berlin', 'Almanya', 'DE',
   'Berlin', 'BSc Computer Engineering (English track)', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   320, '🇩🇪', '15 Temmuz', '[{"source":"QS Europe","rank":30,"year":2025}]'::jsonb, 30, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('navarra-bba', 'University of Navarra', 'İspanya', 'ES',
   'Pamplona', 'BBA (Bilingual English-Spanish)', 'İşletme', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   14000, '🇪🇸', 'Haziran', '[{"source":"QS Europe","rank":28,"year":2025}]'::jsonb, 25, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('taltech-bsc-iba', 'TalTech (Tallinn University of Technology)', 'Estonya', 'EE',
   'Tallinn', 'BSc International Business Administration', 'İşletme', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   4200, '🇪🇪', '1 Haziran', '[{"source":"QS Europe","rank":120,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('masaryk-bsc-economics', 'Masaryk University', 'Çekya', 'CZ',
   'Brno', 'BSc Finance (English)', 'Ekonomi', 'bachelor',
   65, 'IELTS', '5.5', '[{"test":"IELTS","minScore":"5.5"},{"test":"TOEFL","minScore":"72"}]'::jsonb,
   3000, '🇨🇿', '30 Nisan', '[{"source":"QS Europe","rank":110,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('autonoma-madrid-bsc-polsci', 'Universidad Autónoma de Madrid', 'İspanya', 'ES',
   'Madrid', 'BA in Political Science (English track)', 'Siyaset Bilimi', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   6800, '🇪🇸', 'Haziran', '[{"source":"QS Europe","rank":60,"year":2025}]'::jsonb, 45, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('eindhoven-bsc-cs', 'TU Eindhoven', 'Hollanda', 'NL',
   'Eindhoven', 'BSc Computer Science and Engineering', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   13700, '🇳🇱', '15 Ocak', '[{"source":"QS Europe","rank":55,"year":2025}]'::jsonb, 55, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('kit-bsc-me', 'Karlsruhe Institute of Technology (KIT)', 'Almanya', 'DE',
   'Karlsruhe', 'BSc Mechanical Engineering', 'Makine Mühendisliği', 'bachelor',
   78, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   1500, '🇩🇪', '15 Temmuz', '[{"source":"QS Europe","rank":45,"year":2025}]'::jsonb, 45, 'high',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('newcastle-bsc-engineering', 'Newcastle University', 'İngiltere', 'GB',
   'Newcastle', 'BEng Mechanical Engineering', 'Makine Mühendisliği', 'bachelor',
   78, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"90"}]'::jsonb,
   28500, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":72,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('qub-bsc-cs', 'Queen''s University Belfast', 'İngiltere', 'GB',
   'Belfast', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   75, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   17500, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":95,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('tartu-bsc-cs', 'University of Tartu', 'Estonya', 'EE',
   'Tartu', 'BSc Computer Science', 'Bilgisayar Mühendisliği', 'bachelor',
   72, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   5800, '🇪🇪', '15 Nisan', '[{"source":"QS Europe","rank":135,"year":2025}]'::jsonb, 40, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('warsaw-bsc-economics', 'University of Warsaw', 'Polonya', 'PL',
   'Varşova', 'BA in International Economics', 'Ekonomi', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   3200, '🇵🇱', '15 Temmuz', '[{"source":"QS Europe","rank":140,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('masaryk-bsc-ir', 'Masaryk University', 'Çekya', 'CZ',
   'Brno', 'BA International Relations', 'Uluslararası İlişkiler', 'bachelor',
   70, 'IELTS', '6.0', '[{"test":"IELTS","minScore":"6.0"},{"test":"TOEFL","minScore":"80"}]'::jsonb,
   3600, '🇨🇿', '15 Mayıs', '[{"source":"QS Europe","rank":220,"year":2025}]'::jsonb, 55, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL),
  ('york-bsc-economics', 'University of York', 'İngiltere', 'GB',
   'York', 'BSc Economics and Finance', 'Ekonomi', 'bachelor',
   80, 'IELTS', '6.5', '[{"test":"IELTS","minScore":"6.5"},{"test":"TOEFL","minScore":"87"}]'::jsonb,
   25000, '🇬🇧', '14 Ocak (UCAS)', '[{"source":"QS Europe","rank":80,"year":2025}]'::jsonb, 50, 'medium',
   true, NULL, NULL, NULL, NULL, NULL,
   NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  city = EXCLUDED.city,
  program = EXCLUDED.program,
  department = EXCLUDED.department,
  level = EXCLUDED.level,
  required_gpa = EXCLUDED.required_gpa,
  required_language = EXCLUDED.required_language,
  required_language_score = EXCLUDED.required_language_score,
  accepted_languages = EXCLUDED.accepted_languages,
  tuition_eur = EXCLUDED.tuition_eur,
  flag = EXCLUDED.flag,
  deadline = EXCLUDED.deadline,
  rankings = EXCLUDED.rankings,
  acceptance_rate = EXCLUDED.acceptance_rate,
  competitiveness = EXCLUDED.competitiveness,
  data_verified = EXCLUDED.data_verified,
  program_restricted = EXCLUDED.program_restricted,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  image_url = EXCLUDED.image_url,
  duration_years = EXCLUDED.duration_years,
  country_color = EXCLUDED.country_color,
  website = EXCLUDED.website;
