insert into universities
  (id, name, country, country_code, city, program, department, required_gpa, required_language, required_language_score, tuition_eur, flag, deadline)
values
  ('insead-mim', 'INSEAD', 'Fransa', 'FR', 'Fontainebleau', 'Master in Management', 'İşletme', 85, 'IELTS', '7.0', 45000, '🇫🇷', 'Ocak (R1), Mart (R2)'),
  ('hec-paris-mim', 'HEC Paris', 'Fransa', 'FR', 'Paris', 'Master in Management (Grande École)', 'İşletme', 85, 'IELTS', '7.0', 22000, '🇫🇷', 'Ocak (R1), Mart (R2)'),
  ('lbs-mim', 'London Business School', 'İngiltere', 'GB', 'Londra', 'Masters in Management', 'İşletme', 82, 'IELTS', '7.0', 38000, '🇬🇧', 'Ocak (R1), Nisan (R2)'),
  ('escp-mim', 'ESCP Business School', 'Fransa', 'FR', 'Paris', 'Master in Management', 'İşletme', 78, 'IELTS', '6.5', 19500, '🇫🇷', 'Nisan'),
  ('iese-mba', 'IESE Business School', 'İspanya', 'ES', 'Barcelona', 'MBA', 'İşletme', 82, 'IELTS', '7.0', 42000, '🇪🇸', 'Ekim (R1), Ocak (R2)'),
  ('sda-bocconi-mba', 'SDA Bocconi School of Management', 'İtalya', 'IT', 'Milano', 'MBA / Master in Management', 'İşletme', 80, 'IELTS', '7.0', 32000, '🇮🇹', 'Ocak (R1), Nisan (R2)'),
  ('st-gallen-mim', 'University of St. Gallen', 'İsviçre', 'CH', 'St. Gallen', 'Master in Management', 'İşletme', 82, 'IELTS', '7.0', 3400, '🇨🇭', 'Mart'),
  ('edhec-mim', 'EDHEC Business School', 'Fransa', 'FR', 'Nice', 'Master in Management', 'İşletme', 75, 'IELTS', '6.5', 18500, '🇫🇷', 'Nisan'),
  ('emlyon-mim', 'emlyon business school', 'Fransa', 'FR', 'Lyon', 'Master in Management (Grande École)', 'İşletme', 72, 'IELTS', '6.5', 17500, '🇫🇷', 'Nisan'),
  ('esade-mim', 'Esade Business School', 'İspanya', 'ES', 'Barcelona', 'Master in Management', 'İşletme', 78, 'IELTS', '6.5', 24000, '🇪🇸', 'Haziran'),
  ('esmt-berlin-mim', 'ESMT Berlin', 'Almanya', 'DE', 'Berlin', 'Master in Management', 'İşletme', 75, 'IELTS', '6.5', 20000, '🇩🇪', 'Haziran'),
  ('imd-mba', 'IMD Business School', 'İsviçre', 'CH', 'Lozan', 'MBA', 'İşletme', 82, 'IELTS', '7.0', 48000, '🇨🇭', 'Eylül (R1), Ocak (R2)'),
  ('oxford-said-mba', 'Oxford Saïd Business School', 'İngiltere', 'GB', 'Oxford', 'MBA', 'İşletme', 85, 'IELTS', '7.5', 42000, '🇬🇧', 'Eylül (R1), Ocak (R2)'),
  ('mannheim-mim', 'Mannheim Business School', 'Almanya', 'DE', 'Mannheim', 'Mannheim Master in Management', 'İşletme', 75, 'IELTS', '6.5', 1500, '🇩🇪', '31 Mayıs'),
  ('skema-mim', 'SKEMA Business School', 'Fransa', 'FR', 'Lille', 'Master in Management (Grande École)', 'İşletme', 70, 'IELTS', '6.5', 16000, '🇫🇷', 'Mayıs'),
  ('warwick-mim', 'Warwick Business School', 'İngiltere', 'GB', 'Coventry', 'MSc Management', 'İşletme', 78, 'IELTS', '7.0', 32000, '🇬🇧', 'Temmuz'),
  ('sse-stockholm-mim', 'Stockholm School of Economics', 'İsveç', 'SE', 'Stockholm', 'MSc Business & Management', 'İşletme', 78, 'IELTS', '7.0', 0, '🇸🇪', '15 Ocak'),
  ('cambridge-judge-mba', 'Cambridge Judge Business School', 'İngiltere', 'GB', 'Cambridge', 'MBA', 'İşletme', 85, 'IELTS', '7.5', 40000, '🇬🇧', 'Eylül (R1), Ocak (R2)'),
  ('vlerick-mim', 'Vlerick Business School', 'Belçika', 'BE', 'Gent', 'Master in Management', 'İşletme', 72, 'IELTS', '6.5', 18000, '🇧🇪', 'Haziran'),
  ('rsm-erasmus-mim', 'Rotterdam School of Management (Erasmus)', 'Hollanda', 'NL', 'Rotterdam', 'MSc International Management', 'İşletme', 75, 'IELTS', '6.5', 18500, '🇳🇱', '1 Mayıs'),
  ('frankfurt-school-mim', 'Frankfurt School of Finance & Management', 'Almanya', 'DE', 'Frankfurt', 'Master in Management', 'İşletme', 72, 'IELTS', '6.5', 19500, '🇩🇪', '15 Temmuz'),
  ('grenoble-em-mim', 'Grenoble Ecole de Management', 'Fransa', 'FR', 'Grenoble', 'Master in Management (Grande École)', 'İşletme', 70, 'IELTS', '6.5', 15000, '🇫🇷', 'Mayıs'),
  ('audencia-mim', 'Audencia Business School', 'Fransa', 'FR', 'Nantes', 'Master in Management (Grande École)', 'İşletme', 70, 'IELTS', '6.0', 14500, '🇫🇷', 'Mayıs'),
  ('neoma-mim', 'NEOMA Business School', 'Fransa', 'FR', 'Reims', 'Master in Management (Grande École)', 'İşletme', 68, 'IELTS', '6.0', 14000, '🇫🇷', 'Mayıs'),
  ('kedge-mim', 'KEDGE Business School', 'Fransa', 'FR', 'Marsilya', 'Master in Management (Grande École)', 'İşletme', 68, 'IELTS', '6.0', 14000, '🇫🇷', 'Haziran'),
  ('polimi-gsom-mim', 'POLIMI Graduate School of Management', 'İtalya', 'IT', 'Milano', 'International Master in Management', 'İşletme', 72, 'IELTS', '6.5', 16000, '🇮🇹', 'Nisan'),
  ('ie-business-mim', 'IE Business School', 'İspanya', 'ES', 'Madrid', 'Master in Management', 'İşletme', 75, 'IELTS', '7.0', 25000, '🇪🇸', 'Haziran'),
  ('whu-mim', 'WHU – Otto Beisheim School of Management', 'Almanya', 'DE', 'Vallendar', 'Master in Management', 'İşletme', 75, 'IELTS', '6.5', 12000, '🇩🇪', '31 Mayıs'),
  ('wu-vienna-mim', 'WU Vienna University of Economics and Business', 'Avusturya', 'AT', 'Viyana', 'Master in Management', 'İşletme', 72, 'IELTS', '6.5', 1500, '🇦🇹', 'Şubat'),
  ('cranfield-mba', 'Cranfield School of Management', 'İngiltere', 'GB', 'Cranfield', 'MBA', 'İşletme', 75, 'IELTS', '7.0', 38000, '🇬🇧', 'Temmuz'),
  ('alliance-manchester-mim', 'Alliance Manchester Business School', 'İngiltere', 'GB', 'Manchester', 'MSc Management', 'İşletme', 75, 'IELTS', '6.5', 28000, '🇬🇧', 'Temmuz'),
  ('bayes-mim', 'Bayes Business School (City, University of London)', 'İngiltere', 'GB', 'Londra', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 26000, '🇬🇧', 'Temmuz'),
  ('henley-mim', 'Henley Business School', 'İngiltere', 'GB', 'Reading', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 24000, '🇬🇧', 'Temmuz'),
  ('imperial-mim', 'Imperial College Business School', 'İngiltere', 'GB', 'Londra', 'MSc Management', 'İşletme', 82, 'IELTS', '7.0', 34000, '🇬🇧', 'Haziran'),
  ('trinity-dublin-mim', 'Trinity Business School (Trinity College Dublin)', 'İrlanda', 'IE', 'Dublin', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 18000, '🇮🇪', 'Haziran'),
  ('ieseg-mim', 'IESEG School of Management', 'Fransa', 'FR', 'Lille', 'Master in Management (Grande École)', 'İşletme', 68, 'IELTS', '6.0', 13500, '🇫🇷', 'Haziran'),
  ('solvay-mim', 'Solvay Brussels School of Economics & Management', 'Belçika', 'BE', 'Brüksel', 'Master in Management', 'İşletme', 70, 'IELTS', '6.5', 5500, '🇧🇪', 'Haziran'),
  ('icn-mim', 'ICN Business School', 'Fransa', 'FR', 'Nancy', 'Master in Management (Grande École)', 'İşletme', 65, 'IELTS', '6.0', 12000, '🇫🇷', 'Haziran'),
  ('essca-mim', 'ESSCA School of Management', 'Fransa', 'FR', 'Angers', 'Master in Management (Grande École)', 'İşletme', 65, 'IELTS', '6.0', 12000, '🇫🇷', 'Haziran'),
  ('bath-mim', 'University of Bath School of Management', 'İngiltere', 'GB', 'Bath', 'MSc Management', 'İşletme', 75, 'IELTS', '7.0', 28000, '🇬🇧', 'Temmuz'),
  ('paris-school-business', 'Paris School of Business', 'Fransa', 'FR', 'Paris', 'Master in Management (Grande École)', 'İşletme', 65, 'IELTS', '6.0', 13000, '🇫🇷', 'Haziran'),
  ('lse-mim', 'London School of Economics and Political Science (LSE)', 'İngiltere', 'GB', 'Londra', 'MSc Management', 'İşletme', 85, 'IELTS', '7.0', 35000, '🇬🇧', 'Nisan'),
  ('cbs-mim', 'Copenhagen Business School', 'Danimarka', 'DK', 'Kopenhag', 'MSc Business Administration & Innovation', 'İşletme', 72, 'IELTS', '6.5', 0, '🇩🇰', '1 Mart'),
  ('bi-norwegian-mim', 'BI Norwegian Business School', 'Norveç', 'NO', 'Oslo', 'MSc Business', 'İşletme', 72, 'IELTS', '6.5', 0, '🇳🇴', '15 Nisan'),
  ('nhh-mim', 'NHH Norwegian School of Economics', 'Norveç', 'NO', 'Bergen', 'MSc Economics & Business Administration', 'İşletme', 72, 'IELTS', '6.5', 0, '🇳🇴', '1 Nisan'),
  ('aalto-mim', 'Aalto University School of Business', 'Finlandiya', 'FI', 'Helsinki', 'MSc Business & Management', 'İşletme', 72, 'IELTS', '6.5', 15000, '🇫🇮', 'Ocak'),
  ('hanken-mim', 'Hanken School of Economics', 'Finlandiya', 'FI', 'Helsinki', 'MSc Business & Management', 'İşletme', 70, 'IELTS', '6.5', 12000, '🇫🇮', 'Ocak'),
  ('nova-sbe-mim', 'Nova School of Business & Economics', 'Portekiz', 'PT', 'Lizbon', 'Master in Management', 'İşletme', 72, 'IELTS', '6.5', 9500, '🇵🇹', 'Mayıs'),
  ('catolica-lisbon-mim', 'Católica Lisbon School of Business & Economics', 'Portekiz', 'PT', 'Lizbon', 'Master in Management', 'İşletme', 70, 'IELTS', '6.5', 8500, '🇵🇹', 'Mayıs'),
  ('iseg-lisbon-mim', 'ISEG – Lisbon School of Economics & Management', 'Portekiz', 'PT', 'Lizbon', 'Master in Management', 'İşletme', 68, 'IELTS', '6.0', 4500, '🇵🇹', 'Haziran'),
  ('porto-fep-mim', 'University of Porto – Faculty of Economics', 'Portekiz', 'PT', 'Porto', 'Master in Management', 'İşletme', 68, 'IELTS', '6.0', 3500, '🇵🇹', 'Haziran'),
  ('iscte-mim', 'ISCTE Business School', 'Portekiz', 'PT', 'Lizbon', 'Master in Management', 'İşletme', 68, 'IELTS', '6.0', 4000, '🇵🇹', 'Haziran'),
  ('amsterdam-business-mim', 'University of Amsterdam Business School', 'Hollanda', 'NL', 'Amsterdam', 'MSc Business Administration', 'İşletme', 72, 'IELTS', '6.5', 14000, '🇳🇱', '1 Nisan'),
  ('maastricht-mim', 'Maastricht University School of Business and Economics', 'Hollanda', 'NL', 'Maastricht', 'MSc International Business', 'İşletme', 72, 'IELTS', '6.5', 14000, '🇳🇱', '1 Nisan'),
  ('tilburg-mim', 'Tilburg University – School of Economics and Management', 'Hollanda', 'NL', 'Tilburg', 'MSc Management', 'İşletme', 70, 'IELTS', '6.5', 14000, '🇳🇱', '1 Mayıs'),
  ('nyenrode-mim', 'Nyenrode Business Universiteit', 'Hollanda', 'NL', 'Breukelen', 'MSc Management', 'İşletme', 70, 'IELTS', '6.5', 22000, '🇳🇱', 'Haziran'),
  ('ku-leuven-mim', 'KU Leuven – Faculty of Economics and Business', 'Belçika', 'BE', 'Leuven', 'Master of Business Administration', 'İşletme', 72, 'IELTS', '6.5', 3500, '🇧🇪', '1 Mart'),
  ('antwerp-mim', 'Antwerp Management School', 'Belçika', 'BE', 'Antwerp', 'Master in Management', 'İşletme', 70, 'IELTS', '6.5', 15000, '🇧🇪', 'Haziran'),
  ('cologne-mim', 'University of Cologne – Faculty of Management', 'Almanya', 'DE', 'Köln', 'MSc Business Administration', 'İşletme', 72, 'IELTS', '6.5', 0, '🇩🇪', '15 Temmuz'),
  ('goettingen-mim', 'University of Göttingen – Faculty of Business and Economics', 'Almanya', 'DE', 'Göttingen', 'MSc Management', 'İşletme', 70, 'IELTS', '6.5', 0, '🇩🇪', '15 Temmuz'),
  ('fu-berlin-mim', 'Freie Universität Berlin – School of Business & Economics', 'Almanya', 'DE', 'Berlin', 'MSc Management & Marketing', 'İşletme', 72, 'IELTS', '6.5', 0, '🇩🇪', '15 Temmuz'),
  ('hec-lausanne-mim', 'HEC Lausanne (University of Lausanne)', 'İsviçre', 'CH', 'Lozan', 'Master in Management', 'İşletme', 75, 'IELTS', '6.5', 2400, '🇨🇭', 'Nisan'),
  ('zurich-mim', 'University of Zurich – Department of Business Administration', 'İsviçre', 'CH', 'Zürih', 'MSc Management & Economics', 'İşletme', 78, 'IELTS', '7.0', 2600, '🇨🇭', 'Nisan'),
  ('ucd-smurfit-mim', 'UCD Michael Smurfit Graduate Business School', 'İrlanda', 'IE', 'Dublin', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 18000, '🇮🇪', 'Haziran'),
  ('durham-mim', 'Durham University Business School', 'İngiltere', 'GB', 'Durham', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 27000, '🇬🇧', 'Temmuz'),
  ('lancaster-mim', 'Lancaster University Management School', 'İngiltere', 'GB', 'Lancaster', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 25000, '🇬🇧', 'Temmuz'),
  ('edinburgh-mim', 'University of Edinburgh Business School', 'İngiltere', 'GB', 'Edinburgh', 'MSc Management', 'İşletme', 78, 'IELTS', '7.0', 28000, '🇬🇧', 'Haziran'),
  ('nottingham-mim', 'Nottingham University Business School', 'İngiltere', 'GB', 'Nottingham', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 26000, '🇬🇧', 'Temmuz'),
  ('st-andrews-mim', 'University of St Andrews School of Management', 'İngiltere', 'GB', 'St Andrews', 'MLitt Management', 'İşletme', 75, 'IELTS', '7.0', 26000, '🇬🇧', 'Haziran'),
  ('aarhus-mim', 'Aarhus University – School of Business and Social Sciences', 'Danimarka', 'DK', 'Aarhus', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 0, '🇩🇰', '1 Mart'),
  ('lund-mim', 'Lund University School of Economics and Management', 'İsveç', 'SE', 'Lund', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 12000, '🇸🇪', '15 Ocak'),
  ('gothenburg-mim', 'University of Gothenburg School of Business, Economics and Law', 'İsveç', 'SE', 'Göteborg', 'MSc Management', 'İşletme', 70, 'IELTS', '6.5', 11000, '🇸🇪', '15 Ocak'),
  ('barcelona-mim', 'University of Barcelona – Faculty of Economics and Business', 'İspanya', 'ES', 'Barcelona', 'Master in Business Management', 'İşletme', 68, 'IELTS', '6.0', 4500, '🇪🇸', 'Haziran'),
  ('pompeu-fabra-mim', 'Universitat Pompeu Fabra – Barcelona School of Management', 'İspanya', 'ES', 'Barcelona', 'MSc Management', 'İşletme', 72, 'IELTS', '6.5', 12000, '🇪🇸', 'Haziran'),
  ('carlos-iii-mim', 'Universidad Carlos III de Madrid', 'İspanya', 'ES', 'Madrid', 'Master in Management', 'İşletme', 70, 'IELTS', '6.0', 6000, '🇪🇸', 'Haziran'),
  ('navarra-mim', 'University of Navarra – School of Economics and Business', 'İspanya', 'ES', 'Pamplona', 'Master in Management', 'İşletme', 75, 'IELTS', '6.5', 14000, '🇪🇸', 'Haziran'),
  ('kozminski-mim', 'Kozminski University', 'Polonya', 'PL', 'Varşova', 'Master in Management', 'İşletme', 68, 'IELTS', '6.0', 6000, '🇵🇱', 'Temmuz'),
  ('sgh-warsaw-mim', 'SGH Warsaw School of Economics', 'Polonya', 'PL', 'Varşova', 'Master in Management', 'İşletme', 68, 'IELTS', '6.0', 3000, '🇵🇱', 'Temmuz'),
  ('prague-economics-mim', 'Prague University of Economics and Business', 'Çekya', 'CZ', 'Prag', 'Master in Management', 'İşletme', 68, 'IELTS', '6.0', 4000, '🇨🇿', 'Haziran'),
  ('corvinus-mim', 'Corvinus University of Budapest', 'Macaristan', 'HU', 'Budapeşte', 'MSc Management & Leadership', 'İşletme', 68, 'IELTS', '6.0', 4500, '🇭🇺', 'Haziran'),
  ('toulouse-mim', 'Toulouse Business School (TBS Education)', 'Fransa', 'FR', 'Toulouse', 'Master in Management (Grande École)', 'İşletme', 68, 'IELTS', '6.0', 14000, '🇫🇷', 'Haziran'),
  ('montpellier-mim', 'Montpellier Business School', 'Fransa', 'FR', 'Montpellier', 'Master in Management (Grande École)', 'İşletme', 65, 'IELTS', '6.0', 12500, '🇫🇷', 'Haziran'),
  ('em-normandie-mim', 'EM Normandie Business School', 'Fransa', 'FR', 'Le Havre', 'Master in Management (Grande École)', 'İşletme', 65, 'IELTS', '6.0', 12000, '🇫🇷', 'Haziran'),
  ('eth-zurich-cs', 'ETH Zurich', 'İsviçre', 'CH', 'Zürih', 'MSc Computer Science', 'Bilgisayar Mühendisliği', 88, 'IELTS', '7.0', 1300, '🇨🇭', '15 Aralık'),
  ('imperial-cs', 'Imperial College London', 'İngiltere', 'GB', 'Londra', 'MSc Computing', 'Bilgisayar Mühendisliği', 85, 'IELTS', '7.0', 38000, '🇬🇧', 'Mart'),
  ('oxford-cs', 'University of Oxford', 'İngiltere', 'GB', 'Oxford', 'MSc Computer Science', 'Bilgisayar Mühendisliği', 88, 'IELTS', '7.5', 36000, '🇬🇧', 'Ocak'),
  ('cambridge-cs', 'University of Cambridge', 'İngiltere', 'GB', 'Cambridge', 'MPhil Advanced Computer Science', 'Bilgisayar Mühendisliği', 88, 'IELTS', '7.5', 35000, '🇬🇧', 'Aralık'),
  ('epfl-cs', 'EPFL – École polytechnique fédérale de Lausanne', 'İsviçre', 'CH', 'Lozan', 'MSc Computer Science', 'Bilgisayar Mühendisliği', 85, 'IELTS', '7.0', 1300, '🇨🇭', '15 Aralık'),
  ('edinburgh-cs', 'University of Edinburgh', 'İngiltere', 'GB', 'Edinburgh', 'MSc Computer Science', 'Bilgisayar Mühendisliği', 80, 'IELTS', '7.0', 30000, '🇬🇧', 'Nisan'),
  ('ucl-cs', 'UCL (University College London)', 'İngiltere', 'GB', 'Londra', 'MSc Computer Science', 'Bilgisayar Mühendisliği', 80, 'IELTS', '7.0', 33000, '🇬🇧', 'Mart'),
  ('tu-berlin-cs', 'Technische Universität Berlin', 'Almanya', 'DE', 'Berlin', 'MSc Computer Science', 'Bilgisayar Mühendisliği', 75, 'IELTS', '6.5', 0, '🇩🇪', '31 Mayıs'),
  ('tu-eindhoven-cs', 'Eindhoven University of Technology', 'Hollanda', 'NL', 'Eindhoven', 'MSc Computer Science & Engineering', 'Bilgisayar Mühendisliği', 75, 'IELTS', '6.5', 16000, '🇳🇱', '1 Nisan'),
  ('aalto-cs', 'Aalto University', 'Finlandiya', 'FI', 'Helsinki', 'MSc Computer, Communication and Information Sciences', 'Bilgisayar Mühendisliği', 75, 'IELTS', '6.5', 15000, '🇫🇮', 'Ocak'),
  ('dtu-cs', 'Technical University of Denmark (DTU)', 'Danimarka', 'DK', 'Kopenhag', 'MSc Computer Science & Engineering', 'Bilgisayar Mühendisliği', 75, 'IELTS', '6.5', 15000, '🇩🇰', '1 Mart'),
  ('chalmers-cs', 'Chalmers University of Technology', 'İsveç', 'SE', 'Göteborg', 'MSc Computer Science', 'Bilgisayar Mühendisliği', 75, 'IELTS', '6.5', 14000, '🇸🇪', '15 Ocak'),
  ('polito-cs', 'Politecnico di Torino', 'İtalya', 'IT', 'Torino', 'MSc Computer Engineering', 'Bilgisayar Mühendisliği', 70, 'IELTS', '6.0', 3000, '🇮🇹', 'Nisan'),
  ('upc-cs', 'Universitat Politècnica de Catalunya (UPC)', 'İspanya', 'ES', 'Barcelona', 'MSc Computer Science', 'Bilgisayar Mühendisliği', 70, 'IELTS', '6.0', 4500, '🇪🇸', 'Haziran'),
  ('eth-zurich-eng', 'ETH Zurich', 'İsviçre', 'CH', 'Zürih', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 88, 'IELTS', '7.0', 1300, '🇨🇭', '15 Aralık'),
  ('imperial-eng', 'Imperial College London', 'İngiltere', 'GB', 'Londra', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 82, 'IELTS', '6.5', 36000, '🇬🇧', 'Mart'),
  ('epfl-eng', 'EPFL – École polytechnique fédérale de Lausanne', 'İsviçre', 'CH', 'Lozan', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 85, 'IELTS', '7.0', 1300, '🇨🇭', '15 Aralık'),
  ('dtu-eng', 'Technical University of Denmark (DTU)', 'Danimarka', 'DK', 'Kopenhag', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 75, 'IELTS', '6.5', 15000, '🇩🇰', '1 Mart'),
  ('chalmers-eng', 'Chalmers University of Technology', 'İsveç', 'SE', 'Göteborg', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 75, 'IELTS', '6.5', 14000, '🇸🇪', '15 Ocak'),
  ('polito-eng', 'Politecnico di Torino', 'İtalya', 'IT', 'Torino', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 70, 'IELTS', '6.0', 3000, '🇮🇹', 'Nisan'),
  ('tu-wien-eng', 'TU Wien (Vienna University of Technology)', 'Avusturya', 'AT', 'Viyana', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 72, 'IELTS', '6.5', 1500, '🇦🇹', 'Şubat'),
  ('upc-eng', 'Universitat Politècnica de Catalunya (UPC)', 'İspanya', 'ES', 'Barcelona', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 70, 'IELTS', '6.0', 4500, '🇪🇸', 'Haziran'),
  ('university-twente-eng', 'University of Twente', 'Hollanda', 'NL', 'Enschede', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 72, 'IELTS', '6.5', 16000, '🇳🇱', '1 Mayıs'),
  ('stuttgart-eng', 'University of Stuttgart', 'Almanya', 'DE', 'Stuttgart', 'MSc Mechanical Engineering', 'Makine Mühendisliği', 72, 'IELTS', '6.5', 0, '🇩🇪', '15 Temmuz'),
  ('eth-zurich-ee', 'ETH Zurich', 'İsviçre', 'CH', 'Zürih', 'MSc Electrical Engineering & Information Technology', 'Elektrik-Elektronik Mühendisliği', 88, 'IELTS', '7.0', 1300, '🇨🇭', '15 Aralık'),
  ('imperial-ee', 'Imperial College London', 'İngiltere', 'GB', 'Londra', 'MSc Electrical & Electronic Engineering', 'Elektrik-Elektronik Mühendisliği', 82, 'IELTS', '6.5', 36000, '🇬🇧', 'Mart'),
  ('epfl-ee', 'EPFL – École polytechnique fédérale de Lausanne', 'İsviçre', 'CH', 'Lozan', 'MSc Electrical & Electronic Engineering', 'Elektrik-Elektronik Mühendisliği', 85, 'IELTS', '7.0', 1300, '🇨🇭', '15 Aralık'),
  ('tu-delft-ee', 'TU Delft', 'Hollanda', 'NL', 'Delft', 'MSc Electrical Engineering', 'Elektrik-Elektronik Mühendisliği', 75, 'IELTS', '6.5', 2209, '🇳🇱', '1 Nisan'),
  ('kth-ee', 'KTH Royal Institute of Technology', 'İsveç', 'SE', 'Stockholm', 'MSc Electrical Engineering', 'Elektrik-Elektronik Mühendisliği', 75, 'IELTS', '6.5', 13500, '🇸🇪', '15 Ocak'),
  ('eth-zurich-arch', 'ETH Zurich', 'İsviçre', 'CH', 'Zürih', 'MSc Architecture', 'Mimarlık', 85, 'IELTS', '7.0', 1300, '🇨🇭', '15 Aralık'),
  ('ucl-arch', 'UCL – The Bartlett School of Architecture', 'İngiltere', 'GB', 'Londra', 'MArch Architecture', 'Mimarlık', 82, 'IELTS', '7.0', 30000, '🇬🇧', 'Mart'),
  ('tu-wien-arch', 'TU Wien (Vienna University of Technology)', 'Avusturya', 'AT', 'Viyana', 'MSc Architecture', 'Mimarlık', 72, 'IELTS', '6.5', 1500, '🇦🇹', 'Şubat'),
  ('aalborg-arch', 'Aalborg University', 'Danimarka', 'DK', 'Aalborg', 'MSc Architecture & Design', 'Mimarlık', 72, 'IELTS', '6.5', 0, '🇩🇰', '1 Mart'),
  ('lse-economics', 'London School of Economics and Political Science (LSE)', 'İngiltere', 'GB', 'Londra', 'MSc Economics', 'Ekonomi', 88, 'IELTS', '7.0', 35000, '🇬🇧', 'Nisan'),
  ('cambridge-economics', 'University of Cambridge', 'İngiltere', 'GB', 'Cambridge', 'MPhil Economics', 'Ekonomi', 88, 'IELTS', '7.5', 35000, '🇬🇧', 'Aralık'),
  ('oxford-economics', 'University of Oxford', 'İngiltere', 'GB', 'Oxford', 'MPhil Economics', 'Ekonomi', 88, 'IELTS', '7.5', 36000, '🇬🇧', 'Ocak'),
  ('toulouse-economics', 'Toulouse School of Economics (TSE)', 'Fransa', 'FR', 'Toulouse', 'MSc Economics', 'Ekonomi', 80, 'IELTS', '6.5', 6000, '🇫🇷', 'Nisan'),
  ('stockholm-economics', 'Stockholm University', 'İsveç', 'SE', 'Stockholm', 'MSc Economics', 'Ekonomi', 72, 'IELTS', '6.5', 0, '🇸🇪', '15 Ocak'),
  ('tilburg-economics', 'Tilburg University', 'Hollanda', 'NL', 'Tilburg', 'MSc Economics', 'Ekonomi', 72, 'IELTS', '6.5', 14000, '🇳🇱', '1 Mayıs'),
  ('sorbonne-economics', 'Sorbonne Université', 'Fransa', 'FR', 'Paris', 'MSc Economics', 'Ekonomi', 78, 'IELTS', '6.5', 4000, '🇫🇷', 'Nisan'),
  ('zurich-economics', 'University of Zurich', 'İsviçre', 'CH', 'Zürih', 'MSc Economics', 'Ekonomi', 80, 'IELTS', '7.0', 2600, '🇨🇭', 'Nisan'),
  ('oxford-politics', 'University of Oxford', 'İngiltere', 'GB', 'Oxford', 'MPhil Politics', 'Siyaset Bilimi', 88, 'IELTS', '7.5', 36000, '🇬🇧', 'Ocak'),
  ('leiden-politics', 'Leiden University', 'Hollanda', 'NL', 'Leiden', 'MSc Political Science', 'Siyaset Bilimi', 75, 'IELTS', '7.0', 14000, '🇳🇱', '1 Nisan'),
  ('amsterdam-politics', 'University of Amsterdam', 'Hollanda', 'NL', 'Amsterdam', 'MSc Political Science', 'Siyaset Bilimi', 75, 'IELTS', '6.5', 14000, '🇳🇱', '1 Nisan'),
  ('copenhagen-politics', 'University of Copenhagen', 'Danimarka', 'DK', 'Kopenhag', 'MSc Political Science', 'Siyaset Bilimi', 75, 'IELTS', '6.5', 0, '🇩🇰', '1 Mart'),
  ('lse-ir', 'London School of Economics and Political Science (LSE)', 'İngiltere', 'GB', 'Londra', 'MSc International Relations', 'Uluslararası İlişkiler', 85, 'IELTS', '7.0', 35000, '🇬🇧', 'Nisan'),
  ('geneva-ir', 'Graduate Institute Geneva (IHEID)', 'İsviçre', 'CH', 'Cenevre', 'Master in International Affairs', 'Uluslararası İlişkiler', 82, 'IELTS', '7.0', 8000, '🇨🇭', '15 Ocak'),
  ('leiden-ir', 'Leiden University', 'Hollanda', 'NL', 'Den Haag', 'MSc International Relations & Diplomacy', 'Uluslararası İlişkiler', 75, 'IELTS', '7.0', 14000, '🇳🇱', '1 Nisan'),
  ('karolinska-med', 'Karolinska Institute', 'İsveç', 'SE', 'Stockholm', 'MSc Biomedical Sciences', 'Tıp', 82, 'IELTS', '6.5', 19000, '🇸🇪', '15 Ocak'),
  ('heidelberg-med', 'Heidelberg University', 'Almanya', 'DE', 'Heidelberg', 'MSc Molecular Biosciences', 'Tıp', 78, 'IELTS', '6.5', 0, '🇩🇪', '15 Temmuz'),
  ('copenhagen-med', 'University of Copenhagen', 'Danimarka', 'DK', 'Kopenhag', 'MSc Medical Sciences', 'Tıp', 78, 'IELTS', '6.5', 0, '🇩🇰', '1 Mart'),
  ('amsterdam-med', 'University of Amsterdam', 'Hollanda', 'NL', 'Amsterdam', 'MSc Biomedical Sciences', 'Tıp', 75, 'IELTS', '6.5', 14000, '🇳🇱', '1 Nisan'),
  ('oxford-law', 'University of Oxford', 'İngiltere', 'GB', 'Oxford', 'BCL / MJur (Master of Law)', 'Hukuk', 88, 'IELTS', '7.5', 36000, '🇬🇧', 'Ocak'),
  ('cambridge-law', 'University of Cambridge', 'İngiltere', 'GB', 'Cambridge', 'LLM Master of Law', 'Hukuk', 88, 'IELTS', '7.5', 35000, '🇬🇧', 'Aralık'),
  ('leiden-law', 'Leiden University', 'Hollanda', 'NL', 'Leiden', 'LLM European Law', 'Hukuk', 75, 'IELTS', '7.0', 14000, '🇳🇱', '1 Nisan'),
  ('humboldt-law', 'Humboldt University of Berlin', 'Almanya', 'DE', 'Berlin', 'LLM European & International Law', 'Hukuk', 75, 'IELTS', '6.5', 0, '🇩🇪', '15 Temmuz')
on conflict (id) do nothing;
