import type { University } from "@/types";

export const universities: University[] = [
  {
    id: "tu-delft-bsc-ae",
    name: "TU Delft",
    country: "Hollanda",
    countryCode: "NL",
    city: "Delft",
    program: "BSc Aerospace Engineering",
    department: "Havacılık Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 13536,
    flag: "🇳🇱",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 15, year: 2025 }],
    acceptanceRate: 60,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "tu-delft-bsc-cs",
    name: "TU Delft",
    country: "Hollanda",
    countryCode: "NL",
    city: "Delft",
    program: "BSc Computer Science & Engineering",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 13536,
    flag: "🇳🇱",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 15, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "amsterdam-bsc-economics",
    name: "University of Amsterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Amsterdam",
    program: "BSc Economics & Business Economics",
    department: "Ekonomi",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12150,
    flag: "🇳🇱",
    deadline: "1 Nisan",
    rankings: [{ source: "QS Europe", rank: 25, year: 2025 }],
    acceptanceRate: 65,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "amsterdam-bsc-cs",
    name: "University of Amsterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Amsterdam",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12150,
    flag: "🇳🇱",
    deadline: "1 Nisan",
    rankings: [{ source: "QS Europe", rank: 25, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "groningen-bsc-psychology",
    name: "University of Groningen",
    country: "Hollanda",
    countryCode: "NL",
    city: "Groningen",
    program: "BSc Psychology",
    department: "Psikoloji",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11500,
    flag: "🇳🇱",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 45, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "groningen-bsc-ir",
    name: "University of Groningen",
    country: "Hollanda",
    countryCode: "NL",
    city: "Groningen",
    program: "BSc International Relations & International Organization",
    department: "Uluslararası İlişkiler",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11500,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 45, year: 2025 }],
    acceptanceRate: 65,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "maastricht-bsc-business",
    name: "Maastricht University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Maastricht",
    program: "BSc International Business",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11000,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 60, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "eindhoven-bsc-me",
    name: "TU Eindhoven",
    country: "Hollanda",
    countryCode: "NL",
    city: "Eindhoven",
    program: "BSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 13400,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 35, year: 2025 }],
    acceptanceRate: 60,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İtalya — Laurea Triennale (3 yıl, İngilizce) ──

  {
    id: "bocconi-bsc-economics",
    name: "Bocconi University",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "BSc International Economics, Management & Finance",
    department: "Ekonomi",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 14000,
    flag: "🇮🇹",
    deadline: "Ocak (Early), Nisan (Regular)",
    rankings: [{ source: "QS Europe", rank: 16, year: 2025 }],
    acceptanceRate: 15,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "85" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "bocconi-bsc-business",
    name: "Bocconi University",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "BSc International Economics & Management",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 14000,
    flag: "🇮🇹",
    deadline: "Ocak (Early), Nisan (Regular)",
    rankings: [{ source: "QS Europe", rank: 16, year: 2025 }],
    acceptanceRate: 18,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "85" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "polimi-bsc-eng",
    name: "Politecnico di Milano",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "BSc Engineering (TOL test required)",
    department: "Mühendislik",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 3900,
    flag: "🇮🇹",
    deadline: "Temmuz",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "70" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "bologna-bsc-business",
    name: "University of Bologna",
    country: "İtalya",
    countryCode: "IT",
    city: "Bologna",
    program: "BSc Business & Economics (CLABE)",
    department: "Ekonomi",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2900,
    flag: "🇮🇹",
    deadline: "Mayıs",
    rankings: [{ source: "QS Europe", rank: 48, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "70" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Almanya — BSc Programları (İngilizce, ücretsiz/düşük ücret) ──

  {
    id: "tum-bsc-management",
    name: "TU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "BSc Management & Technology",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
    rankings: [{ source: "QS Europe", rank: 19, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "rwth-bsc-business",
    name: "RWTH Aachen",
    country: "Almanya",
    countryCode: "DE",
    city: "Aachen",
    program: "BSc Business Administration (English track)",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
    rankings: [{ source: "QS Europe", rank: 33, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "jacobs-bsc-cs",
    name: "Jacobs University Bremen",
    country: "Almanya",
    countryCode: "DE",
    city: "Bremen",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 20000,
    flag: "🇩🇪",
    deadline: "1 Haziran",
    rankings: [],
    acceptanceRate: 45,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İngiltere — BSc/BA Programları (3 yıl) ──

  {
    id: "ucl-bsc-economics",
    name: "UCL (University College London)",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 30000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 4, year: 2025 }],
    acceptanceRate: 12,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "imperial-bsc-cs",
    name: "Imperial College London",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "BEng Computing",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 90,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 38000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 3, year: 2025 }],
    acceptanceRate: 8,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "edinburgh-bsc-cs",
    name: "University of Edinburgh",
    country: "İngiltere",
    countryCode: "GB",
    city: "Edinburgh",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 28000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 12, year: 2025 }],
    acceptanceRate: 18,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "warwick-bsc-economics",
    name: "University of Warwick",
    country: "İngiltere",
    countryCode: "GB",
    city: "Coventry",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 28000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 22, year: 2025 }],
    acceptanceRate: 15,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "manchester-bsc-business",
    name: "University of Manchester",
    country: "İngiltere",
    countryCode: "GB",
    city: "Manchester",
    program: "BSc International Business, Finance & Economics",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 27500,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 14, year: 2025 }],
    acceptanceRate: 22,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "kcl-bsc-business",
    name: "King's College London",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "BSc Business Management",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 28000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 11, year: 2025 }],
    acceptanceRate: 18,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İsveç — BSc Programları (3 yıl, ücretsiz değil non-EU) ──

  {
    id: "lund-bsc-economics",
    name: "Lund University",
    country: "İsveç",
    countryCode: "SE",
    city: "Lund",
    program: "BSc International Business",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 10000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 28, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Danimarka ──

  {
    id: "cbs-bsc-business",
    name: "Copenhagen Business School",
    country: "Danimarka",
    countryCode: "DK",
    city: "Kopenhag",
    program: "BSc International Business",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12500,
    flag: "🇩🇰",
    deadline: "15 Mart",
    rankings: [{ source: "QS Europe", rank: 53, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "91" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },

  // ── İspanya ──

  {
    id: "ie-bsc-business",
    name: "IE University",
    country: "İspanya",
    countryCode: "ES",
    city: "Madrid",
    program: "Bachelor in Business Administration",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 23900,
    flag: "🇪🇸",
    deadline: "Rolling (erken başvuru önerilir)",
    rankings: [{ source: "QS Europe", rank: 80, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "ie-bsc-cs",
    name: "IE University",
    country: "İspanya",
    countryCode: "ES",
    city: "Madrid",
    program: "Bachelor in Computer Science & AI",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 23900,
    flag: "🇪🇸",
    deadline: "Rolling (erken başvuru önerilir)",
    rankings: [{ source: "QS Europe", rank: 80, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İrlanda ──

  {
    id: "trinity-bsc-business",
    name: "Trinity College Dublin",
    country: "İrlanda",
    countryCode: "IE",
    city: "Dublin",
    program: "BSc Business Studies",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 20700,
    flag: "🇮🇪",
    deadline: "1 Şubat",
    rankings: [{ source: "QS Europe", rank: 42, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "trinity-bsc-cs",
    name: "Trinity College Dublin",
    country: "İrlanda",
    countryCode: "IE",
    city: "Dublin",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 23640,
    flag: "🇮🇪",
    deadline: "1 Şubat",
    rankings: [{ source: "QS Europe", rank: 42, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Çekya ──

  {
    id: "charles-bsc-economics",
    name: "Charles University Prague",
    country: "Çekya",
    countryCode: "CZ",
    city: "Prag",
    program: "BSc Economics & Finance",
    department: "Ekonomi",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 6000,
    flag: "🇨🇿",
    deadline: "30 Nisan",
    rankings: [{ source: "QS Europe", rank: 75, year: 2025 }],
    acceptanceRate: 45,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Macaristan ──

  {
    id: "corvinus-bsc-business",
    name: "Corvinus University of Budapest",
    country: "Macaristan",
    countryCode: "HU",
    city: "Budapeşte",
    program: "BSc International Business",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 4800,
    flag: "🇭🇺",
    deadline: "30 Nisan",
    rankings: [{ source: "QS Europe", rank: 120, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Polonya ──

  {
    id: "kozminski-bsc-management",
    name: "Kozminski University",
    country: "Polonya",
    countryCode: "PL",
    city: "Varşova",
    program: "BSc Management",
    department: "İşletme",
    requiredGPA: 60,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 4900,
    flag: "🇵🇱",
    deadline: "15 Temmuz",
    rankings: [],
    acceptanceRate: 65,
    competitiveness: "low",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Hollanda — Ek BSc Programları ──

  {
    id: "erasmus-bsc-economics",
    name: "Erasmus University Rotterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Rotterdam",
    program: "BSc Economics & Business Economics",
    department: "Ekonomi",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12100,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 32, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "erasmus-bsc-iba",
    name: "Erasmus University Rotterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Rotterdam",
    program: "BSc International Business Administration",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12100,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 32, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "utrecht-bsc-economics",
    name: "Utrecht University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Utrecht",
    program: "BSc Economics & Business Economics",
    department: "Ekonomi",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12500,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 20, year: 2025 }],
    acceptanceRate: 60,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "utrecht-bsc-las",
    name: "Utrecht University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Utrecht",
    program: "BSc Liberal Arts & Sciences",
    department: "Liberal Sanatlar",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12500,
    flag: "🇳🇱",
    deadline: "1 Nisan",
    rankings: [{ source: "QS Europe", rank: 20, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "leiden-bsc-polsci",
    name: "Leiden University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Leiden",
    program: "BSc Political Science",
    department: "Siyaset Bilimi",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12500,
    flag: "🇳🇱",
    deadline: "1 Nisan",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "leiden-bsc-ir",
    name: "Leiden University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Leiden",
    program: "BSc International Relations & Organisations",
    department: "Uluslararası İlişkiler",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12500,
    flag: "🇳🇱",
    deadline: "1 Nisan",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "vu-bsc-ba",
    name: "Vrije Universiteit Amsterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Amsterdam",
    program: "BSc Business Analytics",
    department: "İş Analitiği",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12560,
    flag: "🇳🇱",
    deadline: "1 Nisan",
    rankings: [{ source: "QS Europe", rank: 55, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "vu-bsc-ib",
    name: "Vrije Universiteit Amsterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Amsterdam",
    program: "BSc International Business Administration",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12560,
    flag: "🇳🇱",
    deadline: "1 Nisan",
    rankings: [{ source: "QS Europe", rank: 55, year: 2025 }],
    acceptanceRate: 60,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "tilburg-bsc-iba",
    name: "Tilburg University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Tilburg",
    program: "BSc International Business Administration",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 10700,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 65, year: 2025 }],
    acceptanceRate: 65,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "tilburg-bsc-economics",
    name: "Tilburg University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Tilburg",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 10700,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 65, year: 2025 }],
    acceptanceRate: 65,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "wageningen-bsc-food",
    name: "Wageningen University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Wageningen",
    program: "BSc Food Technology",
    department: "Gıda Teknolojisi",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 13400,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 40, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "radboud-bsc-ba",
    name: "Radboud University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Nijmegen",
    program: "BSc Business Administration",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 11700,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 58, year: 2025 }],
    acceptanceRate: 60,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "twente-bsc-tcs",
    name: "University of Twente",
    country: "Hollanda",
    countryCode: "NL",
    city: "Enschede",
    program: "BSc Technical Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 13750,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 70, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "twente-bsc-iba",
    name: "University of Twente",
    country: "Hollanda",
    countryCode: "NL",
    city: "Enschede",
    program: "BSc International Business Administration",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12750,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 70, year: 2025 }],
    acceptanceRate: 60,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İtalya — Ek BSc Programları ──

  {
    id: "padua-bsc-economics",
    name: "University of Padua",
    country: "İtalya",
    countryCode: "IT",
    city: "Padova",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2800,
    flag: "🇮🇹",
    deadline: "Mayıs",
    rankings: [{ source: "QS Europe", rank: 55, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "trento-bsc-economics",
    name: "University of Trento",
    country: "İtalya",
    countryCode: "IT",
    city: "Trento",
    program: "BSc Economics & Management",
    department: "Ekonomi",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2500,
    flag: "🇮🇹",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 90, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "luiss-bsc-economics",
    name: "LUISS Guido Carli",
    country: "İtalya",
    countryCode: "IT",
    city: "Roma",
    program: "BSc Economics & Business",
    department: "Ekonomi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12000,
    flag: "🇮🇹",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 110, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "luiss-bsc-polsci",
    name: "LUISS Guido Carli",
    country: "İtalya",
    countryCode: "IT",
    city: "Roma",
    program: "BSc Political Science",
    department: "Siyaset Bilimi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12000,
    flag: "🇮🇹",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 110, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "milan-bsc-intpol",
    name: "University of Milan",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "BSc International Politics, Law & Economics",
    department: "Siyaset Bilimi",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 3000,
    flag: "🇮🇹",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 52, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "cafoscari-bsc-dm",
    name: "Ca' Foscari University of Venice",
    country: "İtalya",
    countryCode: "IT",
    city: "Venedik",
    program: "BSc Digital Management",
    department: "Dijital Yönetim",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2800,
    flag: "🇮🇹",
    deadline: "Mayıs",
    rankings: [{ source: "QS Europe", rank: 100, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Almanya — Ek BSc Programları ──

  {
    id: "constructor-bsc-iba",
    name: "Constructor University Bremen",
    country: "Almanya",
    countryCode: "DE",
    city: "Bremen",
    program: "BSc International Business Administration",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 20000,
    flag: "🇩🇪",
    deadline: "1 Haziran",
    rankings: [],
    acceptanceRate: 45,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "constructor-bsc-datasci",
    name: "Constructor University Bremen",
    country: "Almanya",
    countryCode: "DE",
    city: "Bremen",
    program: "BSc Data Science",
    department: "Veri Bilimi",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 20000,
    flag: "🇩🇪",
    deadline: "1 Haziran",
    rankings: [],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "escp-bsc-management",
    name: "ESCP Business School",
    country: "Almanya",
    countryCode: "DE",
    city: "Berlin",
    program: "BSc in Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 17900,
    flag: "🇩🇪",
    deadline: "Haziran (rolling)",
    rankings: [{ source: "QS Europe", rank: 85, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "bard-ba-humanities",
    name: "Bard College Berlin",
    country: "Almanya",
    countryCode: "DE",
    city: "Berlin",
    program: "BA Humanities, Arts & Social Thought",
    department: "Liberal Sanatlar",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 19500,
    flag: "🇩🇪",
    deadline: "15 Mart",
    rankings: [],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "whu-bsc-iba",
    name: "WHU – Otto Beisheim School of Management",
    country: "Almanya",
    countryCode: "DE",
    city: "Vallendar",
    program: "BSc International Business Administration",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 9990,
    flag: "🇩🇪",
    deadline: "15 Mayıs",
    rankings: [{ source: "QS Europe", rank: 95, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "95" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "ebs-bsc-business",
    name: "EBS Universität",
    country: "Almanya",
    countryCode: "DE",
    city: "Wiesbaden",
    program: "BSc Business Studies",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 9480,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
    rankings: [],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İngiltere — Ek BSc/BA Programları ──

  {
    id: "bristol-bsc-economics",
    name: "University of Bristol",
    country: "İngiltere",
    countryCode: "GB",
    city: "Bristol",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 25000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 18, year: 2025 }],
    acceptanceRate: 18,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "leeds-bsc-business",
    name: "University of Leeds",
    country: "İngiltere",
    countryCode: "GB",
    city: "Leeds",
    program: "BSc Business Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 26500,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 35, year: 2025 }],
    acceptanceRate: 22,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "birmingham-bsc-business",
    name: "University of Birmingham",
    country: "İngiltere",
    countryCode: "GB",
    city: "Birmingham",
    program: "BSc Business Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 24000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 20,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "bath-bsc-ba",
    name: "University of Bath",
    country: "İngiltere",
    countryCode: "GB",
    city: "Bath",
    program: "BSc Business Administration",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 22000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 15,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "loughborough-bsc-be",
    name: "Loughborough University",
    country: "İngiltere",
    countryCode: "GB",
    city: "Loughborough",
    program: "BSc Business Economics",
    department: "Ekonomi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 21000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 60, year: 2025 }],
    acceptanceRate: 28,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "glasgow-bsc-cs",
    name: "University of Glasgow",
    country: "İngiltere",
    countryCode: "GB",
    city: "Glasgow",
    program: "BSc Computing Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 27500,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 26, year: 2025 }],
    acceptanceRate: 20,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "lse-bsc-economics",
    name: "London School of Economics (LSE)",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 90,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 32000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 6, year: 2025 }],
    acceptanceRate: 8,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "107" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "oxford-ba-em",
    name: "University of Oxford",
    country: "İngiltere",
    countryCode: "GB",
    city: "Oxford",
    program: "BA Economics & Management",
    department: "Ekonomi",
    requiredGPA: 92,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 38000,
    flag: "🇬🇧",
    deadline: "15 Ekim (UCAS erken)",
    rankings: [{ source: "QS Europe", rank: 1, year: 2025 }],
    acceptanceRate: 5,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.5" }, { test: "TOEFL", minScore: "110" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "cambridge-ba-economics",
    name: "University of Cambridge",
    country: "İngiltere",
    countryCode: "GB",
    city: "Cambridge",
    program: "BA Economics",
    department: "Ekonomi",
    requiredGPA: 92,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 37000,
    flag: "🇬🇧",
    deadline: "15 Ekim (UCAS erken)",
    rankings: [{ source: "QS Europe", rank: 2, year: 2025 }],
    acceptanceRate: 6,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.5" }, { test: "TOEFL", minScore: "110" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },

  // ── İsveç — Ek BSc Programları ──

  {
    id: "stockholm-bsc-be",
    name: "Stockholm University",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "BSc Business & Economics",
    department: "Ekonomi",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 45, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "uppsala-bsc-be",
    name: "Uppsala University",
    country: "İsveç",
    countryCode: "SE",
    city: "Uppsala",
    program: "BSc Business & Economics",
    department: "Ekonomi",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 10500,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 38, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Danimarka — Ek BSc Programları ──

  {
    id: "aarhus-bsc-ba",
    name: "Aarhus University",
    country: "Danimarka",
    countryCode: "DK",
    city: "Aarhus",
    program: "BSc Business Administration",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 13500,
    flag: "🇩🇰",
    deadline: "15 Mart",
    rankings: [{ source: "QS Europe", rank: 42, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "sdu-bsc-eng",
    name: "University of Southern Denmark",
    country: "Danimarka",
    countryCode: "DK",
    city: "Odense",
    program: "BSc Engineering (Electronics)",
    department: "Mühendislik",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 13000,
    flag: "🇩🇰",
    deadline: "15 Mart",
    rankings: [{ source: "QS Europe", rank: 80, year: 2025 }],
    acceptanceRate: 45,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Finlandiya — BSc Programları ──

  {
    id: "aalto-bsc-ib",
    name: "Aalto University",
    country: "Finlandiya",
    countryCode: "FI",
    city: "Helsinki",
    program: "BSc International Business",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇫🇮",
    deadline: "9 Ocak",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 20,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "helsinki-bsc-science",
    name: "University of Helsinki",
    country: "Finlandiya",
    countryCode: "FI",
    city: "Helsinki",
    program: "BSc Science (English track)",
    department: "Fen Bilimleri",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 15000,
    flag: "🇫🇮",
    deadline: "9 Ocak",
    rankings: [{ source: "QS Europe", rank: 35, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İspanya — Ek BSc Programları ──

  {
    id: "esade-bba",
    name: "ESADE Business School",
    country: "İspanya",
    countryCode: "ES",
    city: "Barselona",
    program: "Bachelor in Business Administration (BBA)",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18200,
    flag: "🇪🇸",
    deadline: "Rolling (erken başvuru önerilir)",
    rankings: [{ source: "QS Europe", rank: 75, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "ub-bsc-business",
    name: "University of Barcelona",
    country: "İspanya",
    countryCode: "ES",
    city: "Barselona",
    program: "BSc International Business (English)",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 5500,
    flag: "🇪🇸",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 48, year: 2025 }],
    acceptanceRate: 45,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Avusturya — BSc Programları ──

  {
    id: "modul-bsc-im",
    name: "Modul University Vienna",
    country: "Avusturya",
    countryCode: "AT",
    city: "Viyana",
    program: "BSc International Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 13900,
    flag: "🇦🇹",
    deadline: "Rolling",
    rankings: [],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "wu-bsc-be",
    name: "WU Vienna University of Economics and Business",
    country: "Avusturya",
    countryCode: "AT",
    city: "Viyana",
    program: "BSc Business & Economics (English track)",
    department: "Ekonomi",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 1500,
    flag: "🇦🇹",
    deadline: "1 Şubat",
    rankings: [{ source: "QS Europe", rank: 55, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Belçika — BSc Programları ──

  {
    id: "kuleuven-bsc-beng",
    name: "KU Leuven",
    country: "Belçika",
    countryCode: "BE",
    city: "Leuven",
    program: "BSc Business Engineering (English)",
    department: "İşletme Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 6000,
    flag: "🇧🇪",
    deadline: "1 Mart",
    rankings: [{ source: "QS Europe", rank: 24, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "ghent-bsc-beng",
    name: "Ghent University",
    country: "Belçika",
    countryCode: "BE",
    city: "Gent",
    program: "BSc Business Engineering",
    department: "İşletme Mühendisliği",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 5300,
    flag: "🇧🇪",
    deadline: "1 Mart",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Portekiz — BSc Programları ──

  {
    id: "nova-bsc-economics",
    name: "Nova School of Business & Economics",
    country: "Portekiz",
    countryCode: "PT",
    city: "Lizbon",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 7500,
    flag: "🇵🇹",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 70, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "nova-bsc-management",
    name: "Nova School of Business & Economics",
    country: "Portekiz",
    countryCode: "PT",
    city: "Lizbon",
    program: "BSc Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 7500,
    flag: "🇵🇹",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 70, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "catolica-bsc-management",
    name: "Católica Lisbon School of Business & Economics",
    country: "Portekiz",
    countryCode: "PT",
    city: "Lizbon",
    program: "BSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 6800,
    flag: "🇵🇹",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 85, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İrlanda — Ek BSc Programları ──

  {
    id: "ucd-bsc-business",
    name: "University College Dublin (UCD)",
    country: "İrlanda",
    countryCode: "IE",
    city: "Dublin",
    program: "BSc Business",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 19400,
    flag: "🇮🇪",
    deadline: "1 Şubat",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "ucd-bsc-cs",
    name: "University College Dublin (UCD)",
    country: "İrlanda",
    countryCode: "IE",
    city: "Dublin",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 22900,
    flag: "🇮🇪",
    deadline: "1 Şubat",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "ucc-bsc-bis",
    name: "University College Cork",
    country: "İrlanda",
    countryCode: "IE",
    city: "Cork",
    program: "BSc Business Information Systems",
    department: "Bilgi Sistemleri",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 17000,
    flag: "🇮🇪",
    deadline: "1 Şubat",
    rankings: [{ source: "QS Europe", rank: 75, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Hollanda — Ek BSc Programları (2. grup) ──

  {
    id: "erasmus-bsc-econometrics",
    name: "Erasmus University Rotterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Rotterdam",
    program: "BSc Econometrics & Operations Research",
    department: "Ekonometri",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12100,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 32, year: 2025 }],
    acceptanceRate: 45,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "groningen-bsc-economics",
    name: "University of Groningen",
    country: "Hollanda",
    countryCode: "NL",
    city: "Groningen",
    program: "BSc Economics & Business Economics",
    department: "Ekonomi",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11500,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 45, year: 2025 }],
    acceptanceRate: 60,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "maastricht-bsc-economics",
    name: "Maastricht University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Maastricht",
    program: "BSc Econometrics & Operations Research",
    department: "Ekonometri",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11000,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [{ source: "QS Europe", rank: 60, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "leiden-bsc-psychology",
    name: "Leiden University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Leiden",
    program: "BSc Psychology (English)",
    department: "Psikoloji",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12500,
    flag: "🇳🇱",
    deadline: "1 Nisan",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },

  // ── İtalya — Ek BSc Programları (2. grup) ──

  {
    id: "bologna-bsc-polsci",
    name: "University of Bologna",
    country: "İtalya",
    countryCode: "IT",
    city: "Bologna",
    program: "BSc Diplomatic & International Sciences",
    department: "Uluslararası İlişkiler",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2900,
    flag: "🇮🇹",
    deadline: "Mayıs",
    rankings: [{ source: "QS Europe", rank: 48, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "torino-bsc-business",
    name: "University of Turin",
    country: "İtalya",
    countryCode: "IT",
    city: "Torino",
    program: "BSc Business & Management (English)",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2700,
    flag: "🇮🇹",
    deadline: "Temmuz",
    rankings: [{ source: "QS Europe", rank: 80, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "polimi-bsc-design",
    name: "Politecnico di Milano",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "BSc Design (English track)",
    department: "Tasarım",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 3900,
    flag: "🇮🇹",
    deadline: "Temmuz",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 45,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "70" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },

  // ── Almanya — Ek BSc Programları (2. grup) ──

  {
    id: "constructor-bsc-biochem",
    name: "Constructor University Bremen",
    country: "Almanya",
    countryCode: "DE",
    city: "Bremen",
    program: "BSc Biochemistry & Cell Biology",
    department: "Biyokimya",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 20000,
    flag: "🇩🇪",
    deadline: "1 Haziran",
    rankings: [],
    acceptanceRate: 45,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "tum-bsc-cs",
    name: "TU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "BSc Informatics (English track)",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
    rankings: [{ source: "QS Europe", rank: 19, year: 2025 }],
    acceptanceRate: 20,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },

  // ── İngiltere — Ek BSc/BA Programları (2. grup) ──

  {
    id: "exeter-bsc-business",
    name: "University of Exeter",
    country: "İngiltere",
    countryCode: "GB",
    city: "Exeter",
    program: "BSc Business",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 23000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 40, year: 2025 }],
    acceptanceRate: 20,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "nottingham-bsc-economics",
    name: "University of Nottingham",
    country: "İngiltere",
    countryCode: "GB",
    city: "Nottingham",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 24000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 32, year: 2025 }],
    acceptanceRate: 22,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "sheffield-bsc-cs",
    name: "University of Sheffield",
    country: "İngiltere",
    countryCode: "GB",
    city: "Sheffield",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 76,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 26200,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 38, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "southampton-bsc-cs",
    name: "University of Southampton",
    country: "İngiltere",
    countryCode: "GB",
    city: "Southampton",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 76,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 25000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 36, year: 2025 }],
    acceptanceRate: 24,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Finlandiya — Ek BSc Programları ──

  {
    id: "aalto-bsc-datasci",
    name: "Aalto University",
    country: "Finlandiya",
    countryCode: "FI",
    city: "Helsinki",
    program: "BSc Data Science",
    department: "Veri Bilimi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇫🇮",
    deadline: "9 Ocak",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 18,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },

  // ── Belçika — Ek BSc Programları ──

  {
    id: "kuleuven-bsc-economics",
    name: "KU Leuven",
    country: "Belçika",
    countryCode: "BE",
    city: "Leuven",
    program: "BSc Economics (English)",
    department: "Ekonomi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 6000,
    flag: "🇧🇪",
    deadline: "1 Mart",
    rankings: [{ source: "QS Europe", rank: 24, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Danimarka — Ek BSc Programları ──

  {
    id: "dtu-bsc-eng",
    name: "Technical University of Denmark (DTU)",
    country: "Danimarka",
    countryCode: "DK",
    city: "Kopenhag",
    program: "BSc General Engineering (English)",
    department: "Mühendislik",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇩🇰",
    deadline: "15 Mart",
    rankings: [{ source: "QS Europe", rank: 38, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İsveç — Ek BSc Programları ──

  {
    id: "kth-bsc-eng",
    name: "KTH Royal Institute of Technology",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "BSc Information & Communication Technology",
    department: "Bilişim Teknolojileri",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 16000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 28, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Top Üniversiteler — Bachelor Eklentileri ──

  {
    id: "sciences-po-bsc-polsci",
    name: "Sciences Po",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Political Science (Bachelor)",
    department: "Siyaset Bilimi",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 0,
    flag: "🇫🇷",
    deadline: "5 Ocak",
    rankings: [{ source: "QS Europe", rank: 2, year: 2025 }],
    acceptanceRate: 12,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    description: "Sciences Po'nun 3 yıllık lisans programı. İlk 2 yıl Fransa, 3. yıl yurt dışı. Ücretsiz (gelire göre).",
    level: "bachelor",
  },
  {
    id: "sciences-po-bsc-economics",
    name: "Sciences Po",
    country: "Fransa",
    countryCode: "FR",
    city: "Reims",
    program: "Economics & Society (Bachelor)",
    department: "Ekonomi",
    requiredGPA: 83,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 0,
    flag: "🇫🇷",
    deadline: "5 Ocak",
    rankings: [{ source: "QS Europe", rank: 2, year: 2025 }],
    acceptanceRate: 15,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    description: "Reims kampüsünde İngilizce lisans. Avrupa-Kuzey Amerika odaklı.",
    level: "bachelor",
  },
  {
    id: "lmu-bsc-economics",
    name: "LMU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "Economics (Bachelor)",
    department: "Ekonomi",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 140,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
    rankings: [{ source: "QS Europe", rank: 59, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "85" }],
    dataVerified: true,
    description: "LMU'nun İngilizce destekli ekonomi lisans programı. Çok düşük ücret.",
    level: "bachelor",
  },
  {
    id: "mannheim-bsc-business",
    name: "University of Mannheim",
    country: "Almanya",
    countryCode: "DE",
    city: "Mannheim",
    program: "Business Administration (Bachelor)",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 1500,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
    rankings: [{ source: "QS Europe", rank: 25, year: 2025 }],
    acceptanceRate: 17,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    description: "Almanya'nın en iyi işletme fakültesi. Non-EU öğrenciler için 1500€/dönem.",
    level: "bachelor",
  },
  {
    id: "st-gallen-bsc-ia",
    name: "University of St. Gallen",
    country: "İsviçre",
    countryCode: "CH",
    city: "St. Gallen",
    program: "International Affairs (Bachelor)",
    department: "Uluslararası İlişkiler",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 3460,
    flag: "🇨🇭",
    deadline: "30 Nisan",
    rankings: [{ source: "QS Europe", rank: 15, year: 2025 }],
    acceptanceRate: 20,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    description: "HSG'nin İngilizce lisans programı. CHF 3326/dönem (~3460€).",
    level: "bachelor",
  },
  {
    id: "karolinska-bsc-biomed",
    name: "Karolinska Institute",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "Biomedicine (Bachelor)",
    department: "Tıp Bilimleri",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 19000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 7, year: 2025 }],
    acceptanceRate: 8,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    description: "Dünya'nın en iyi tıp okullarından biri. İngilizce Biyomedikal Bilimler lisansı.",
    level: "bachelor",
  },

  // ── Silinen Okulların Bachelor Programları ──

  {
    id: "aalborg-bsc-electronics",
    name: "Aalborg University",
    country: "Danimarka",
    countryCode: "DK",
    city: "Aalborg",
    program: "BSc Electronics & IT",
    department: "Elektrik-Elektronik Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 13300,
    flag: "🇩🇰",
    deadline: "15 Mart",
    rankings: [{ source: "QS Europe", rank: 130, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "aalborg-bsc-energy",
    name: "Aalborg University",
    country: "Danimarka",
    countryCode: "DK",
    city: "Aalborg",
    program: "BSc Energy Engineering",
    department: "Mühendislik",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 13300,
    flag: "🇩🇰",
    deadline: "15 Mart",
    rankings: [{ source: "QS Europe", rank: 130, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "antwerp-bsc-be",
    name: "University of Antwerp",
    country: "Belçika",
    countryCode: "BE",
    city: "Antwerp",
    program: "BSc Business Engineering",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 6000,
    flag: "🇧🇪",
    deadline: "1 Mart",
    rankings: [{ source: "QS Europe", rank: 95, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "durham-bsc-cs",
    name: "Durham University",
    country: "İngiltere",
    countryCode: "GB",
    city: "Durham",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 29000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 25, year: 2025 }],
    acceptanceRate: 20,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "durham-bsc-economics",
    name: "Durham University",
    country: "İngiltere",
    countryCode: "GB",
    city: "Durham",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 24500,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 25, year: 2025 }],
    acceptanceRate: 22,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "lancaster-bsc-business",
    name: "Lancaster University",
    country: "İngiltere",
    countryCode: "GB",
    city: "Lancaster",
    program: "BSc Business Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 24000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "lancaster-bsc-cs",
    name: "Lancaster University",
    country: "İngiltere",
    countryCode: "GB",
    city: "Lancaster",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 27000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "standrews-bsc-cs",
    name: "University of St Andrews",
    country: "İngiltere",
    countryCode: "GB",
    city: "St Andrews",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 28000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 18, year: 2025 }],
    acceptanceRate: 15,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "standrews-bsc-economics",
    name: "University of St Andrews",
    country: "İngiltere",
    countryCode: "GB",
    city: "St Andrews",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 26000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 18, year: 2025 }],
    acceptanceRate: 12,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "standrews-bsc-ir",
    name: "University of St Andrews",
    country: "İngiltere",
    countryCode: "GB",
    city: "St Andrews",
    program: "MA International Relations",
    department: "Uluslararası İlişkiler",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 26000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 18, year: 2025 }],
    acceptanceRate: 12,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "polito-bsc-eng",
    name: "Politecnico di Torino",
    country: "İtalya",
    countryCode: "IT",
    city: "Torino",
    program: "BSc Engineering (English track)",
    department: "Mühendislik",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2800,
    flag: "🇮🇹",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 55, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "polito-bsc-auto",
    name: "Politecnico di Torino",
    country: "İtalya",
    countryCode: "IT",
    city: "Torino",
    program: "BSc Automotive Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2800,
    flag: "🇮🇹",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 55, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "carlos-iii-bsc-economics",
    name: "Universidad Carlos III de Madrid",
    country: "İspanya",
    countryCode: "ES",
    city: "Madrid",
    program: "BSc Economics (English track)",
    department: "Ekonomi",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 6500,
    flag: "🇪🇸",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 70, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "carlos-iii-bsc-business",
    name: "Universidad Carlos III de Madrid",
    country: "İspanya",
    countryCode: "ES",
    city: "Madrid",
    program: "BSc Business Administration (Bilingual)",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 6500,
    flag: "🇪🇸",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 70, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "pompeu-fabra-bsc-economics",
    name: "Universitat Pompeu Fabra",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "BSc Economics (English track)",
    department: "Ekonomi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 6800,
    flag: "🇪🇸",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 45, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "gothenburg-bsc-se",
    name: "University of Gothenburg",
    country: "İsveç",
    countryCode: "SE",
    city: "Göteborg",
    program: "BSc Software Engineering & Management",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11500,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 65, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "sse-bsc-economics",
    name: "Stockholm School of Economics",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "BSc Business & Economics",
    department: "Ekonomi",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 18000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 10,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "7.0" }, { test: "TOEFL", minScore: "100" }],
    dataVerified: true,
    programRestricted: true,
    level: "bachelor",
  },
  {
    id: "iscte-bsc-management",
    name: "ISCTE – University Institute of Lisbon",
    country: "Portekiz",
    countryCode: "PT",
    city: "Lizbon",
    program: "BSc Management (English track)",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 4500,
    flag: "🇵🇹",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 140, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "sgh-bsc-ib",
    name: "SGH Warsaw School of Economics",
    country: "Polonya",
    countryCode: "PL",
    city: "Varşova",
    program: "BSc International Business",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 3200,
    flag: "🇵🇱",
    deadline: "15 Temmuz",
    rankings: [{ source: "QS Europe", rank: 160, year: 2025 }],
    acceptanceRate: 55,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "sgh-bsc-economics",
    name: "SGH Warsaw School of Economics",
    country: "Polonya",
    countryCode: "PL",
    city: "Varşova",
    program: "BSc Quantitative Economics",
    department: "Ekonomi",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 3200,
    flag: "🇵🇱",
    deadline: "15 Temmuz",
    rankings: [{ source: "QS Europe", rank: 160, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "copenhagen-bsc-economics",
    name: "University of Copenhagen",
    country: "Danimarka",
    countryCode: "DK",
    city: "Kopenhag",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12000,
    flag: "🇩🇰",
    deadline: "15 Mart",
    rankings: [{ source: "QS Europe", rank: 17, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "essec-bba",
    name: "ESSEC Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Cergy (Paris)",
    program: "BBA (Bachelor in Business Administration)",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 17600,
    flag: "🇫🇷",
    deadline: "10 Ocak",
    rankings: [{ source: "QS Europe", rank: 12, year: 2025 }],
    acceptanceRate: 20,
    competitiveness: "very_high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }, { test: "DELF/DALF", minScore: "B2" }],
    dataVerified: true,
    description: "4 yıllık İngilizce/Fransızca çift dilli BBA. Fransa'nın en prestijli işletme okullarından. Staj zorunlu.",
    level: "bachelor",
  },

  // ── Fransız Grande Écoles — BBA Programları ──

  {
    id: "edhec-bba",
    name: "EDHEC Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Nice",
    program: "BBA (Bachelor in Business Administration)",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 14500,
    flag: "🇫🇷",
    deadline: "Mart",
    rankings: [{ source: "QS Europe", rank: 15, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }, { test: "DELF/DALF", minScore: "B2" }],
    dataVerified: true,
    description: "4 yıllık İngilizce BBA. Nice kampüsünde. 2 staj zorunlu.",
    level: "bachelor",
  },
  {
    id: "skema-bba",
    name: "SKEMA Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Sophia Antipolis",
    program: "Global BBA",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12900,
    flag: "🇫🇷",
    deadline: "Mart",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }, { test: "DELF/DALF", minScore: "B2" }],
    dataVerified: true,
    description: "4 yıllık Global BBA. 6 kampüs (Fransa, ABD, Çin, Brezilya, Güney Afrika). İngilizce.",
    level: "bachelor",
  },
  {
    id: "emlyon-bba",
    name: "emlyon business school",
    country: "Fransa",
    countryCode: "FR",
    city: "Lyon",
    program: "Global BBA",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 15500,
    flag: "🇫🇷",
    deadline: "Mart",
    rankings: [{ source: "QS Europe", rank: 20, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }, { test: "DELF/DALF", minScore: "B2" }],
    dataVerified: true,
    description: "4 yıllık Global BBA. Lyon + yurt dışı kampüs rotasyonu.",
    level: "bachelor",
  },
  {
    id: "ieseg-bba",
    name: "IESEG School of Management",
    country: "Fransa",
    countryCode: "FR",
    city: "Lille",
    program: "Bachelor in International Business",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 11950,
    flag: "🇫🇷",
    deadline: "Mart",
    rankings: [{ source: "QS Europe", rank: 33, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }, { test: "DELF/DALF", minScore: "B2" }],
    dataVerified: true,
    description: "3 yıllık İngilizce lisans. AACSB ve EQUIS akreditasyonlu.",
    level: "bachelor",
  },
  {
    id: "neoma-bba",
    name: "NEOMA Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Reims",
    program: "Global BBA",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12800,
    flag: "🇫🇷",
    deadline: "Mart",
    rankings: [{ source: "QS Europe", rank: 40, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }, { test: "DELF/DALF", minScore: "B2" }],
    dataVerified: true,
    description: "4 yıllık Global BBA. Reims veya Rouen kampüsü.",
    level: "bachelor",
  },
  {
    id: "kedge-bba",
    name: "KEDGE Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Marsilya",
    program: "International BBA",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 11500,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 45, year: 2025 }],
    acceptanceRate: 45,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }, { test: "DELF/DALF", minScore: "B2" }],
    dataVerified: true,
    description: "4 yıllık International BBA. Marsilya + Bordeaux kampüsleri.",
    level: "bachelor",
  },
  {
    id: "audencia-bba",
    name: "Audencia Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Nantes",
    program: "Bachelor in Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 11200,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 38, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }, { test: "DELF/DALF", minScore: "B2" }],
    dataVerified: true,
    description: "3 yıllık İngilizce Bachelor in Management. Triple akreditasyon (AACSB, EQUIS, AMBA).",
    level: "bachelor",
  },

  // ── Nordic — Eksik Programlar ──

  {
    id: "tampere-bsc-tech",
    name: "Tampere University",
    country: "Finlandiya",
    countryCode: "FI",
    city: "Tampere",
    program: "BSc Science & Engineering",
    department: "Mühendislik",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 10000,
    flag: "🇫🇮",
    deadline: "10 Ocak",
    rankings: [{ source: "QS Europe", rank: 85, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "turku-bsc-tech",
    name: "University of Turku",
    country: "Finlandiya",
    countryCode: "FI",
    city: "Turku",
    program: "BSc Information & Communication Technology",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 10000,
    flag: "🇫🇮",
    deadline: "10 Ocak",
    rankings: [{ source: "QS Europe", rank: 100, year: 2025 }],
    acceptanceRate: 40,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "linkoping-bsc-se",
    name: "Linköping University",
    country: "İsveç",
    countryCode: "SE",
    city: "Linköping",
    program: "BSc Software Engineering",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11500,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS Europe", rank: 75, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "bi-norwegian-bba",
    name: "BI Norwegian Business School",
    country: "Norveç",
    countryCode: "NO",
    city: "Oslo",
    program: "Bachelor in Business Administration",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 9500,
    flag: "🇳🇴",
    deadline: "15 Nisan",
    rankings: [{ source: "QS Europe", rank: 55, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "nhh-bba",
    name: "NHH Norwegian School of Economics",
    country: "Norveç",
    countryCode: "NO",
    city: "Bergen",
    program: "Bachelor in Economics & Business Administration",
    department: "Ekonomi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇳🇴",
    deadline: "15 Nisan",
    rankings: [{ source: "QS Europe", rank: 50, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    description: "Norveç'in en iyi işletme okulu. Non-EU için de ücretsiz.",
    level: "bachelor",
  },

  // ── UK — Eksik Russell Group ──

  {
    id: "queen-mary-bsc-economics",
    name: "Queen Mary University of London",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 22000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 40, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "92" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "york-bsc-cs",
    name: "University of York",
    country: "İngiltere",
    countryCode: "GB",
    city: "York",
    program: "BSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 25000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 35, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "87" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "liverpool-bsc-business",
    name: "University of Liverpool",
    country: "İngiltere",
    countryCode: "GB",
    city: "Liverpool",
    program: "BSc Business Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 21000,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 42, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },
  {
    id: "sussex-bsc-economics",
    name: "University of Sussex",
    country: "İngiltere",
    countryCode: "GB",
    city: "Brighton",
    program: "BSc Economics",
    department: "Ekonomi",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 20500,
    flag: "🇬🇧",
    deadline: "15 Ocak (UCAS)",
    rankings: [{ source: "QS Europe", rank: 48, year: 2025 }],
    acceptanceRate: 35,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "88" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── İtalya — Eksik Programlar ──

  {
    id: "sapienza-bsc-economics",
    name: "Sapienza Università di Roma",
    country: "İtalya",
    countryCode: "IT",
    city: "Roma",
    program: "BSc Economics (English track)",
    department: "Ekonomi",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2800,
    flag: "🇮🇹",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 42, year: 2025 }],
    acceptanceRate: 45,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    description: "Dünyanın en eski üniversitelerinden. Çok düşük ücret.",
    level: "bachelor",
  },
  {
    id: "pavia-bsc-eng",
    name: "University of Pavia",
    country: "İtalya",
    countryCode: "IT",
    city: "Pavia",
    program: "BSc Bioengineering (English)",
    department: "Mühendislik",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2500,
    flag: "🇮🇹",
    deadline: "Nisan",
    rankings: [{ source: "QS Europe", rank: 90, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },

  // ── Almanya — Eksik Programlar ──

  {
    id: "tu-berlin-bsc-cs",
    name: "Technische Universität Berlin",
    country: "Almanya",
    countryCode: "DE",
    city: "Berlin",
    program: "BSc Computer Engineering (English track)",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 320,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
    rankings: [{ source: "QS Europe", rank: 30, year: 2025 }],
    acceptanceRate: 30,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.0" }, { test: "TOEFL", minScore: "80" }],
    dataVerified: true,
    description: "Berlin'in en büyük teknik üniversitesi. Çok düşük ücret.",
    level: "bachelor",
  },

  // ── İspanya — Eksik Programlar ──

  {
    id: "navarra-bba",
    name: "University of Navarra",
    country: "İspanya",
    countryCode: "ES",
    city: "Pamplona",
    program: "BBA (Bilingual English-Spanish)",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇪🇸",
    deadline: "Haziran",
    rankings: [{ source: "QS Europe", rank: 28, year: 2025 }],
    acceptanceRate: 25,
    competitiveness: "high",
    acceptedLanguages: [{ test: "IELTS", minScore: "6.5" }, { test: "TOEFL", minScore: "90" }],
    dataVerified: true,
    description: "İspanya'nın en iyi özel üniversitesi. IESE'nin bağlı olduğu üniversite.",
    level: "bachelor",
  },

  // ── Baltık / Orta Avrupa ──

  {
    id: "taltech-bsc-iba",
    name: "TalTech (Tallinn University of Technology)",
    country: "Estonya",
    countryCode: "EE",
    city: "Tallinn",
    program: "BSc International Business Administration",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 4200,
    flag: "🇪🇪",
    deadline: "1 Haziran",
    rankings: [{ source: "QS Europe", rank: 120, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    description: "Estonya'nın en iyi teknik üniversitesi. Uygun fiyat.",
    level: "bachelor",
  },
  {
    id: "masaryk-bsc-economics",
    name: "Masaryk University",
    country: "Çekya",
    countryCode: "CZ",
    city: "Brno",
    program: "BSc Finance (English)",
    department: "Ekonomi",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 3000,
    flag: "🇨🇿",
    deadline: "30 Nisan",
    rankings: [{ source: "QS Europe", rank: 110, year: 2025 }],
    acceptanceRate: 50,
    competitiveness: "medium",
    acceptedLanguages: [{ test: "IELTS", minScore: "5.5" }, { test: "TOEFL", minScore: "72" }],
    dataVerified: true,
    level: "bachelor",
  },
];
