import type { University } from "@/types";

export const universities: University[] = [
  {
    id: "tu-delft-cs",
    name: "TU Delft",
    country: "Hollanda",
    countryCode: "NL",
    city: "Delft",
    program: "Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 2209,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "tu-delft-arch",
    name: "TU Delft",
    country: "Hollanda",
    countryCode: "NL",
    city: "Delft",
    program: "Architecture",
    department: "Mimarlık",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 2209,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "groningen-business",
    name: "University of Groningen",
    country: "Hollanda",
    countryCode: "NL",
    city: "Groningen",
    program: "International Business",
    department: "İşletme",
    requiredGPA: 62,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 2209,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
  },
  {
    id: "polimi-cs",
    name: "Politecnico di Milano",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "Computer Science & Engineering",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 3000,
    flag: "🇮🇹",
    deadline: "Şubat (erken), Nisan (geç)",
  },
  {
    id: "polimi-arch",
    name: "Politecnico di Milano",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "Architecture",
    department: "Mimarlık",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 3500,
    flag: "🇮🇹",
    deadline: "Mart",
  },
  {
    id: "bocconi-economics",
    name: "Bocconi University",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "Economics",
    department: "Ekonomi",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 14500,
    flag: "🇮🇹",
    deadline: "Ocak (erken), Nisan (geç)",
    rankings: [
      { source: "FT", rank: 6, year: 2025 },
      { source: "QS", rank: 18, year: 2025 },
    ],
  },
  {
    id: "bologna-eng",
    name: "University of Bologna",
    country: "İtalya",
    countryCode: "IT",
    city: "Bologna",
    program: "Engineering",
    department: "Mühendislik",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2900,
    flag: "🇮🇹",
    deadline: "Mayıs",
  },
  {
    id: "tum-cs",
    name: "TU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
  },
  {
    id: "tum-ee",
    name: "TU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "Electrical Engineering",
    department: "Elektrik-Elektronik Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "TestDaF",
    requiredLanguageScore: "4",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
  },
  {
    id: "lmu-business",
    name: "LMU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "Business Administration",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "TestDaF",
    requiredLanguageScore: "4",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
  },
  {
    id: "rwth-aachen",
    name: "RWTH Aachen",
    country: "Almanya",
    countryCode: "DE",
    city: "Aachen",
    program: "Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 72,
    requiredLanguage: "TestDaF",
    requiredLanguageScore: "4",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "1 Mart",
  },
  {
    id: "sciences-po",
    name: "Sciences Po",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Political Science",
    department: "Siyaset Bilimi",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 14000,
    flag: "🇫🇷",
    deadline: "Şubat",
  },
  {
    id: "essec",
    name: "ESSEC Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Business Administration",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 16000,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 7, year: 2025 },
    ],
  },
  {
    id: "ie-university",
    name: "IE University",
    country: "İspanya",
    countryCode: "ES",
    city: "Madrid",
    program: "International Relations",
    department: "Uluslararası İlişkiler",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18000,
    flag: "🇪🇸",
    deadline: "Haziran",
  },
  {
    id: "kth-stockholm",
    name: "KTH Royal Institute",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "Engineering",
    department: "Mühendislik",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 13500,
    flag: "🇸🇪",
    deadline: "15 Ocak",
  },

  // ── European Business Schools (FT & QS Rankings 2025) ──

  {
    id: "insead-mim",
    name: "INSEAD",
    country: "Fransa",
    countryCode: "FR",
    city: "Fontainebleau",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 45000,
    flag: "🇫🇷",
    deadline: "Ocak (R1), Mart (R2)",
    rankings: [
      { source: "FT", rank: 1, year: 2025 },
      { source: "QS", rank: 4, year: 2025 },
    ],
  },
  {
    id: "hec-paris-mim",
    name: "HEC Paris",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 22000,
    flag: "🇫🇷",
    deadline: "Ocak (R1), Mart (R2)",
    rankings: [
      { source: "FT", rank: 2, year: 2025 },
      { source: "QS", rank: 7, year: 2025 },
    ],
  },
  {
    id: "lbs-mim",
    name: "London Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "Masters in Management",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 38000,
    flag: "🇬🇧",
    deadline: "Ocak (R1), Nisan (R2)",
    rankings: [
      { source: "FT", rank: 3, year: 2025 },
      { source: "QS", rank: 6, year: 2025 },
    ],
  },
  {
    id: "escp-mim",
    name: "ESCP Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 19500,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 4, year: 2025 },
      { source: "QS", rank: 12, year: 2025 },
    ],
  },
  {
    id: "iese-mba",
    name: "IESE Business School",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 42000,
    flag: "🇪🇸",
    deadline: "Ekim (R1), Ocak (R2)",
    rankings: [
      { source: "FT", rank: 5, year: 2025 },
      { source: "QS", rank: 10, year: 2025 },
    ],
  },
  {
    id: "sda-bocconi-mba",
    name: "SDA Bocconi School of Management",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "MBA / Master in Management",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 32000,
    flag: "🇮🇹",
    deadline: "Ocak (R1), Nisan (R2)",
    rankings: [
      { source: "FT", rank: 6, year: 2025 },
      { source: "QS", rank: 18, year: 2025 },
    ],
  },
  {
    id: "st-gallen-mim",
    name: "University of St. Gallen",
    country: "İsviçre",
    countryCode: "CH",
    city: "St. Gallen",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 3400,
    flag: "🇨🇭",
    deadline: "Mart",
    rankings: [
      { source: "FT", rank: 8, year: 2025 },
      { source: "QS", rank: 15, year: 2025 },
    ],
  },
  {
    id: "edhec-mim",
    name: "EDHEC Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Nice",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18500,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 9, year: 2025 },
    ],
  },
  {
    id: "emlyon-mim",
    name: "emlyon business school",
    country: "Fransa",
    countryCode: "FR",
    city: "Lyon",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 17500,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 10, year: 2025 },
    ],
  },
  {
    id: "esade-mim",
    name: "Esade Business School",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 24000,
    flag: "🇪🇸",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 11, year: 2025 },
      { source: "QS", rank: 14, year: 2025 },
    ],
  },
  {
    id: "esmt-berlin-mim",
    name: "ESMT Berlin",
    country: "Almanya",
    countryCode: "DE",
    city: "Berlin",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 20000,
    flag: "🇩🇪",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 12, year: 2025 },
    ],
  },
  {
    id: "imd-mba",
    name: "IMD Business School",
    country: "İsviçre",
    countryCode: "CH",
    city: "Lozan",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 48000,
    flag: "🇨🇭",
    deadline: "Eylül (R1), Ocak (R2)",
    rankings: [
      { source: "FT", rank: 13, year: 2025 },
      { source: "QS", rank: 20, year: 2025 },
    ],
  },
  {
    id: "oxford-said-mba",
    name: "Oxford Saïd Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Oxford",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 42000,
    flag: "🇬🇧",
    deadline: "Eylül (R1), Ocak (R2)",
    rankings: [
      { source: "FT", rank: 14, year: 2025 },
      { source: "QS", rank: 8, year: 2025 },
    ],
  },
  {
    id: "mannheim-mim",
    name: "Mannheim Business School",
    country: "Almanya",
    countryCode: "DE",
    city: "Mannheim",
    program: "Mannheim Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 1500,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
    rankings: [
      { source: "FT", rank: 15, year: 2025 },
      { source: "QS", rank: 25, year: 2025 },
    ],
  },
  {
    id: "skema-mim",
    name: "SKEMA Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Lille",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 16000,
    flag: "🇫🇷",
    deadline: "Mayıs",
    rankings: [
      { source: "FT", rank: 16, year: 2025 },
    ],
  },
  {
    id: "warwick-mim",
    name: "Warwick Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Coventry",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 32000,
    flag: "🇬🇧",
    deadline: "Temmuz",
    rankings: [
      { source: "FT", rank: 18, year: 2025 },
      { source: "QS", rank: 30, year: 2025 },
    ],
  },
  {
    id: "sse-stockholm-mim",
    name: "Stockholm School of Economics",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "MSc Business & Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 0,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [
      { source: "FT", rank: 19, year: 2025 },
    ],
  },
  {
    id: "cambridge-judge-mba",
    name: "Cambridge Judge Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Cambridge",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 40000,
    flag: "🇬🇧",
    deadline: "Eylül (R1), Ocak (R2)",
    rankings: [
      { source: "FT", rank: 22, year: 2025 },
      { source: "QS", rank: 5, year: 2025 },
    ],
  },
  {
    id: "vlerick-mim",
    name: "Vlerick Business School",
    country: "Belçika",
    countryCode: "BE",
    city: "Gent",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18000,
    flag: "🇧🇪",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 25, year: 2025 },
    ],
  },
  {
    id: "rsm-erasmus-mim",
    name: "Rotterdam School of Management (Erasmus)",
    country: "Hollanda",
    countryCode: "NL",
    city: "Rotterdam",
    program: "MSc International Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18500,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [
      { source: "FT", rank: 33, year: 2025 },
      { source: "QS", rank: 35, year: 2025 },
    ],
  },
  {
    id: "frankfurt-school-mim",
    name: "Frankfurt School of Finance & Management",
    country: "Almanya",
    countryCode: "DE",
    city: "Frankfurt",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 19500,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
    rankings: [
      { source: "FT", rank: 32, year: 2025 },
    ],
  },
  {
    id: "grenoble-em-mim",
    name: "Grenoble Ecole de Management",
    country: "Fransa",
    countryCode: "FR",
    city: "Grenoble",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇫🇷",
    deadline: "Mayıs",
    rankings: [
      { source: "FT", rank: 24, year: 2025 },
    ],
  },
  {
    id: "audencia-mim",
    name: "Audencia Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Nantes",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 14500,
    flag: "🇫🇷",
    deadline: "Mayıs",
    rankings: [
      { source: "FT", rank: 26, year: 2025 },
    ],
  },
  {
    id: "neoma-mim",
    name: "NEOMA Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Reims",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 14000,
    flag: "🇫🇷",
    deadline: "Mayıs",
    rankings: [
      { source: "FT", rank: 28, year: 2025 },
    ],
  },
  {
    id: "kedge-mim",
    name: "KEDGE Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Marsilya",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 14000,
    flag: "🇫🇷",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 32, year: 2025 },
    ],
  },
  {
    id: "polimi-gsom-mim",
    name: "POLIMI Graduate School of Management",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "International Master in Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 16000,
    flag: "🇮🇹",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 35, year: 2025 },
    ],
  },
  {
    id: "ie-business-mim",
    name: "IE Business School",
    country: "İspanya",
    countryCode: "ES",
    city: "Madrid",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 25000,
    flag: "🇪🇸",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 21, year: 2025 },
      { source: "QS", rank: 16, year: 2025 },
    ],
  },
  {
    id: "whu-mim",
    name: "WHU – Otto Beisheim School of Management",
    country: "Almanya",
    countryCode: "DE",
    city: "Vallendar",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12000,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
    rankings: [
      { source: "FT", rank: 20, year: 2025 },
    ],
  },
  {
    id: "wu-vienna-mim",
    name: "WU Vienna University of Economics and Business",
    country: "Avusturya",
    countryCode: "AT",
    city: "Viyana",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 1500,
    flag: "🇦🇹",
    deadline: "Şubat",
    rankings: [
      { source: "FT", rank: 41, year: 2025 },
    ],
  },
  {
    id: "cranfield-mba",
    name: "Cranfield School of Management",
    country: "İngiltere",
    countryCode: "GB",
    city: "Cranfield",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 38000,
    flag: "🇬🇧",
    deadline: "Temmuz",
    rankings: [
      { source: "FT", rank: 27, year: 2025 },
    ],
  },

  // ── FT Ranked #34–#69 ──

  {
    id: "alliance-manchester-mim",
    name: "Alliance Manchester Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Manchester",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 28000,
    flag: "🇬🇧",
    deadline: "Temmuz",
    rankings: [{ source: "FT", rank: 34, year: 2025 }],
  },
  {
    id: "bayes-mim",
    name: "Bayes Business School (City, University of London)",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 26000,
    flag: "🇬🇧",
    deadline: "Temmuz",
    rankings: [{ source: "FT", rank: 34, year: 2025 }],
  },
  {
    id: "henley-mim",
    name: "Henley Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Reading",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 24000,
    flag: "🇬🇧",
    deadline: "Temmuz",
    rankings: [{ source: "FT", rank: 36, year: 2025 }],
  },
  {
    id: "imperial-mim",
    name: "Imperial College Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 34000,
    flag: "🇬🇧",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 38, year: 2025 },
      { source: "QS", rank: 9, year: 2025 },
    ],
  },
  {
    id: "trinity-dublin-mim",
    name: "Trinity Business School (Trinity College Dublin)",
    country: "İrlanda",
    countryCode: "IE",
    city: "Dublin",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18000,
    flag: "🇮🇪",
    deadline: "Haziran",
    rankings: [{ source: "FT", rank: 43, year: 2025 }],
  },
  {
    id: "ieseg-mim",
    name: "IESEG School of Management",
    country: "Fransa",
    countryCode: "FR",
    city: "Lille",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 13500,
    flag: "🇫🇷",
    deadline: "Haziran",
    rankings: [{ source: "FT", rank: 47, year: 2025 }],
  },
  {
    id: "solvay-mim",
    name: "Solvay Brussels School of Economics & Management",
    country: "Belçika",
    countryCode: "BE",
    city: "Brüksel",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 5500,
    flag: "🇧🇪",
    deadline: "Haziran",
    rankings: [{ source: "FT", rank: 54, year: 2025 }],
  },
  {
    id: "icn-mim",
    name: "ICN Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Nancy",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12000,
    flag: "🇫🇷",
    deadline: "Haziran",
    rankings: [{ source: "FT", rank: 64, year: 2025 }],
  },
  {
    id: "essca-mim",
    name: "ESSCA School of Management",
    country: "Fransa",
    countryCode: "FR",
    city: "Angers",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12000,
    flag: "🇫🇷",
    deadline: "Haziran",
    rankings: [{ source: "FT", rank: 66, year: 2025 }],
  },
  {
    id: "bath-mim",
    name: "University of Bath School of Management",
    country: "İngiltere",
    countryCode: "GB",
    city: "Bath",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 28000,
    flag: "🇬🇧",
    deadline: "Temmuz",
    rankings: [{ source: "FT", rank: 67, year: 2025 }],
  },
  {
    id: "paris-school-business",
    name: "Paris School of Business",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 13000,
    flag: "🇫🇷",
    deadline: "Haziran",
    rankings: [{ source: "FT", rank: 69, year: 2025 }],
  },

  // ── QS Europe Top Schools + Nordic / Iberian / Eastern European ──

  {
    id: "lse-mim",
    name: "London School of Economics and Political Science (LSE)",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 35000,
    flag: "🇬🇧",
    deadline: "Nisan",
    rankings: [{ source: "QS", rank: 11, year: 2025 }],
  },
  {
    id: "cbs-mim",
    name: "Copenhagen Business School",
    country: "Danimarka",
    countryCode: "DK",
    city: "Kopenhag",
    program: "MSc Business Administration & Innovation",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇰",
    deadline: "1 Mart",
  },
  {
    id: "bi-norwegian-mim",
    name: "BI Norwegian Business School",
    country: "Norveç",
    countryCode: "NO",
    city: "Oslo",
    program: "MSc Business",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇳🇴",
    deadline: "15 Nisan",
  },
  {
    id: "nhh-mim",
    name: "NHH Norwegian School of Economics",
    country: "Norveç",
    countryCode: "NO",
    city: "Bergen",
    program: "MSc Economics & Business Administration",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇳🇴",
    deadline: "1 Nisan",
  },
  {
    id: "aalto-mim",
    name: "Aalto University School of Business",
    country: "Finlandiya",
    countryCode: "FI",
    city: "Helsinki",
    program: "MSc Business & Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇫🇮",
    deadline: "Ocak",
  },
  {
    id: "hanken-mim",
    name: "Hanken School of Economics",
    country: "Finlandiya",
    countryCode: "FI",
    city: "Helsinki",
    program: "MSc Business & Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12000,
    flag: "🇫🇮",
    deadline: "Ocak",
  },
  {
    id: "nova-sbe-mim",
    name: "Nova School of Business & Economics",
    country: "Portekiz",
    countryCode: "PT",
    city: "Lizbon",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 9500,
    flag: "🇵🇹",
    deadline: "Mayıs",
  },
  {
    id: "catolica-lisbon-mim",
    name: "Católica Lisbon School of Business & Economics",
    country: "Portekiz",
    countryCode: "PT",
    city: "Lizbon",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 8500,
    flag: "🇵🇹",
    deadline: "Mayıs",
  },
  {
    id: "iseg-lisbon-mim",
    name: "ISEG – Lisbon School of Economics & Management",
    country: "Portekiz",
    countryCode: "PT",
    city: "Lizbon",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 4500,
    flag: "🇵🇹",
    deadline: "Haziran",
  },
  {
    id: "porto-fep-mim",
    name: "University of Porto – Faculty of Economics",
    country: "Portekiz",
    countryCode: "PT",
    city: "Porto",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 3500,
    flag: "🇵🇹",
    deadline: "Haziran",
  },
  {
    id: "iscte-mim",
    name: "ISCTE Business School",
    country: "Portekiz",
    countryCode: "PT",
    city: "Lizbon",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 4000,
    flag: "🇵🇹",
    deadline: "Haziran",
  },
  {
    id: "amsterdam-business-mim",
    name: "University of Amsterdam Business School",
    country: "Hollanda",
    countryCode: "NL",
    city: "Amsterdam",
    program: "MSc Business Administration",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "maastricht-mim",
    name: "Maastricht University School of Business and Economics",
    country: "Hollanda",
    countryCode: "NL",
    city: "Maastricht",
    program: "MSc International Business",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "tilburg-mim",
    name: "Tilburg University – School of Economics and Management",
    country: "Hollanda",
    countryCode: "NL",
    city: "Tilburg",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
  },
  {
    id: "nyenrode-mim",
    name: "Nyenrode Business Universiteit",
    country: "Hollanda",
    countryCode: "NL",
    city: "Breukelen",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 22000,
    flag: "🇳🇱",
    deadline: "Haziran",
  },
  {
    id: "ku-leuven-mim",
    name: "KU Leuven – Faculty of Economics and Business",
    country: "Belçika",
    countryCode: "BE",
    city: "Leuven",
    program: "Master of Business Administration",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 3500,
    flag: "🇧🇪",
    deadline: "1 Mart",
  },
  {
    id: "antwerp-mim",
    name: "Antwerp Management School",
    country: "Belçika",
    countryCode: "BE",
    city: "Antwerp",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇧🇪",
    deadline: "Haziran",
  },
  {
    id: "cologne-mim",
    name: "University of Cologne – Faculty of Management",
    country: "Almanya",
    countryCode: "DE",
    city: "Köln",
    program: "MSc Business Administration",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
  },
  {
    id: "goettingen-mim",
    name: "University of Göttingen – Faculty of Business and Economics",
    country: "Almanya",
    countryCode: "DE",
    city: "Göttingen",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
  },
  {
    id: "fu-berlin-mim",
    name: "Freie Universität Berlin – School of Business & Economics",
    country: "Almanya",
    countryCode: "DE",
    city: "Berlin",
    program: "MSc Management & Marketing",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
  },
  {
    id: "hec-lausanne-mim",
    name: "HEC Lausanne (University of Lausanne)",
    country: "İsviçre",
    countryCode: "CH",
    city: "Lozan",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 2400,
    flag: "🇨🇭",
    deadline: "Nisan",
  },
  {
    id: "zurich-mim",
    name: "University of Zurich – Department of Business Administration",
    country: "İsviçre",
    countryCode: "CH",
    city: "Zürih",
    program: "MSc Management & Economics",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 2600,
    flag: "🇨🇭",
    deadline: "Nisan",
  },
  {
    id: "ucd-smurfit-mim",
    name: "UCD Michael Smurfit Graduate Business School",
    country: "İrlanda",
    countryCode: "IE",
    city: "Dublin",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18000,
    flag: "🇮🇪",
    deadline: "Haziran",
  },
  {
    id: "durham-mim",
    name: "Durham University Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Durham",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 27000,
    flag: "🇬🇧",
    deadline: "Temmuz",
  },
  {
    id: "lancaster-mim",
    name: "Lancaster University Management School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Lancaster",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 25000,
    flag: "🇬🇧",
    deadline: "Temmuz",
  },
  {
    id: "edinburgh-mim",
    name: "University of Edinburgh Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Edinburgh",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 28000,
    flag: "🇬🇧",
    deadline: "Haziran",
  },
  {
    id: "nottingham-mim",
    name: "Nottingham University Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Nottingham",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 26000,
    flag: "🇬🇧",
    deadline: "Temmuz",
  },
  {
    id: "st-andrews-mim",
    name: "University of St Andrews School of Management",
    country: "İngiltere",
    countryCode: "GB",
    city: "St Andrews",
    program: "MLitt Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 26000,
    flag: "🇬🇧",
    deadline: "Haziran",
  },
  {
    id: "aarhus-mim",
    name: "Aarhus University – School of Business and Social Sciences",
    country: "Danimarka",
    countryCode: "DK",
    city: "Aarhus",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇰",
    deadline: "1 Mart",
  },
  {
    id: "lund-mim",
    name: "Lund University School of Economics and Management",
    country: "İsveç",
    countryCode: "SE",
    city: "Lund",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
  },
  {
    id: "gothenburg-mim",
    name: "University of Gothenburg School of Business, Economics and Law",
    country: "İsveç",
    countryCode: "SE",
    city: "Göteborg",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 11000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
  },
  {
    id: "barcelona-mim",
    name: "University of Barcelona – Faculty of Economics and Business",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "Master in Business Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 4500,
    flag: "🇪🇸",
    deadline: "Haziran",
  },
  {
    id: "pompeu-fabra-mim",
    name: "Universitat Pompeu Fabra – Barcelona School of Management",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 12000,
    flag: "🇪🇸",
    deadline: "Haziran",
  },
  {
    id: "carlos-iii-mim",
    name: "Universidad Carlos III de Madrid",
    country: "İspanya",
    countryCode: "ES",
    city: "Madrid",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 6000,
    flag: "🇪🇸",
    deadline: "Haziran",
  },
  {
    id: "navarra-mim",
    name: "University of Navarra – School of Economics and Business",
    country: "İspanya",
    countryCode: "ES",
    city: "Pamplona",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇪🇸",
    deadline: "Haziran",
  },
  {
    id: "kozminski-mim",
    name: "Kozminski University",
    country: "Polonya",
    countryCode: "PL",
    city: "Varşova",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 6000,
    flag: "🇵🇱",
    deadline: "Temmuz",
  },
  {
    id: "sgh-warsaw-mim",
    name: "SGH Warsaw School of Economics",
    country: "Polonya",
    countryCode: "PL",
    city: "Varşova",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 3000,
    flag: "🇵🇱",
    deadline: "Temmuz",
  },
  {
    id: "prague-economics-mim",
    name: "Prague University of Economics and Business",
    country: "Çekya",
    countryCode: "CZ",
    city: "Prag",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 4000,
    flag: "🇨🇿",
    deadline: "Haziran",
  },
  {
    id: "corvinus-mim",
    name: "Corvinus University of Budapest",
    country: "Macaristan",
    countryCode: "HU",
    city: "Budapeşte",
    program: "MSc Management & Leadership",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 4500,
    flag: "🇭🇺",
    deadline: "Haziran",
  },
  {
    id: "toulouse-mim",
    name: "Toulouse Business School (TBS Education)",
    country: "Fransa",
    countryCode: "FR",
    city: "Toulouse",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 68,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 14000,
    flag: "🇫🇷",
    deadline: "Haziran",
  },
  {
    id: "montpellier-mim",
    name: "Montpellier Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Montpellier",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12500,
    flag: "🇫🇷",
    deadline: "Haziran",
  },
  {
    id: "em-normandie-mim",
    name: "EM Normandie Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Le Havre",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 12000,
    flag: "🇫🇷",
    deadline: "Haziran",
  },

  // ══════════════════════════════════════════════════════════════
  // QS Europe Top Universities — Engineering, CS, Sciences, etc.
  // ══════════════════════════════════════════════════════════════

  // ── Computer Science / Bilgisayar Mühendisliği ──

  {
    id: "eth-zurich-cs",
    name: "ETH Zurich",
    country: "İsviçre",
    countryCode: "CH",
    city: "Zürih",
    program: "MSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 1300,
    flag: "🇨🇭",
    deadline: "15 Aralık",
    rankings: [{ source: "QS", rank: 1, year: 2025 }],
  },
  {
    id: "imperial-cs",
    name: "Imperial College London",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc Computing",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 38000,
    flag: "🇬🇧",
    deadline: "Mart",
    rankings: [{ source: "QS", rank: 2, year: 2025 }],
  },
  {
    id: "oxford-cs",
    name: "University of Oxford",
    country: "İngiltere",
    countryCode: "GB",
    city: "Oxford",
    program: "MSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 36000,
    flag: "🇬🇧",
    deadline: "Ocak",
    rankings: [{ source: "QS", rank: 3, year: 2025 }],
  },
  {
    id: "cambridge-cs",
    name: "University of Cambridge",
    country: "İngiltere",
    countryCode: "GB",
    city: "Cambridge",
    program: "MPhil Advanced Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 35000,
    flag: "🇬🇧",
    deadline: "Aralık",
    rankings: [{ source: "QS", rank: 4, year: 2025 }],
  },
  {
    id: "epfl-cs",
    name: "EPFL – École polytechnique fédérale de Lausanne",
    country: "İsviçre",
    countryCode: "CH",
    city: "Lozan",
    program: "MSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 1300,
    flag: "🇨🇭",
    deadline: "15 Aralık",
    rankings: [{ source: "QS", rank: 10, year: 2025 }],
  },
  {
    id: "edinburgh-cs",
    name: "University of Edinburgh",
    country: "İngiltere",
    countryCode: "GB",
    city: "Edinburgh",
    program: "MSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 30000,
    flag: "🇬🇧",
    deadline: "Nisan",
    rankings: [{ source: "QS", rank: 6, year: 2025 }],
  },
  {
    id: "ucl-cs",
    name: "UCL (University College London)",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 33000,
    flag: "🇬🇧",
    deadline: "Mart",
    rankings: [{ source: "QS", rank: 5, year: 2025 }],
  },
  {
    id: "tu-berlin-cs",
    name: "Technische Universität Berlin",
    country: "Almanya",
    countryCode: "DE",
    city: "Berlin",
    program: "MSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
  },
  {
    id: "tu-eindhoven-cs",
    name: "Eindhoven University of Technology",
    country: "Hollanda",
    countryCode: "NL",
    city: "Eindhoven",
    program: "MSc Computer Science & Engineering",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 16000,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "aalto-cs",
    name: "Aalto University",
    country: "Finlandiya",
    countryCode: "FI",
    city: "Helsinki",
    program: "MSc Computer, Communication and Information Sciences",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇫🇮",
    deadline: "Ocak",
  },
  {
    id: "dtu-cs",
    name: "Technical University of Denmark (DTU)",
    country: "Danimarka",
    countryCode: "DK",
    city: "Kopenhag",
    program: "MSc Computer Science & Engineering",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇩🇰",
    deadline: "1 Mart",
  },
  {
    id: "chalmers-cs",
    name: "Chalmers University of Technology",
    country: "İsveç",
    countryCode: "SE",
    city: "Göteborg",
    program: "MSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
  },
  {
    id: "polito-cs",
    name: "Politecnico di Torino",
    country: "İtalya",
    countryCode: "IT",
    city: "Torino",
    program: "MSc Computer Engineering",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 3000,
    flag: "🇮🇹",
    deadline: "Nisan",
  },
  {
    id: "upc-cs",
    name: "Universitat Politècnica de Catalunya (UPC)",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "MSc Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 4500,
    flag: "🇪🇸",
    deadline: "Haziran",
  },

  // ── Engineering / Mühendislik ──

  {
    id: "eth-zurich-eng",
    name: "ETH Zurich",
    country: "İsviçre",
    countryCode: "CH",
    city: "Zürih",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 1300,
    flag: "🇨🇭",
    deadline: "15 Aralık",
    rankings: [{ source: "QS", rank: 1, year: 2025 }],
  },
  {
    id: "imperial-eng",
    name: "Imperial College London",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 36000,
    flag: "🇬🇧",
    deadline: "Mart",
    rankings: [{ source: "QS", rank: 2, year: 2025 }],
  },
  {
    id: "epfl-eng",
    name: "EPFL – École polytechnique fédérale de Lausanne",
    country: "İsviçre",
    countryCode: "CH",
    city: "Lozan",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 1300,
    flag: "🇨🇭",
    deadline: "15 Aralık",
    rankings: [{ source: "QS", rank: 10, year: 2025 }],
  },
  {
    id: "dtu-eng",
    name: "Technical University of Denmark (DTU)",
    country: "Danimarka",
    countryCode: "DK",
    city: "Kopenhag",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 15000,
    flag: "🇩🇰",
    deadline: "1 Mart",
  },
  {
    id: "chalmers-eng",
    name: "Chalmers University of Technology",
    country: "İsveç",
    countryCode: "SE",
    city: "Göteborg",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
  },
  {
    id: "polito-eng",
    name: "Politecnico di Torino",
    country: "İtalya",
    countryCode: "IT",
    city: "Torino",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 3000,
    flag: "🇮🇹",
    deadline: "Nisan",
  },
  {
    id: "tu-wien-eng",
    name: "TU Wien (Vienna University of Technology)",
    country: "Avusturya",
    countryCode: "AT",
    city: "Viyana",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 1500,
    flag: "🇦🇹",
    deadline: "Şubat",
  },
  {
    id: "upc-eng",
    name: "Universitat Politècnica de Catalunya (UPC)",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 4500,
    flag: "🇪🇸",
    deadline: "Haziran",
  },
  {
    id: "university-twente-eng",
    name: "University of Twente",
    country: "Hollanda",
    countryCode: "NL",
    city: "Enschede",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 16000,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
  },
  {
    id: "stuttgart-eng",
    name: "University of Stuttgart",
    country: "Almanya",
    countryCode: "DE",
    city: "Stuttgart",
    program: "MSc Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
  },

  // ── Electrical Engineering / Elektrik-Elektronik Mühendisliği ──

  {
    id: "eth-zurich-ee",
    name: "ETH Zurich",
    country: "İsviçre",
    countryCode: "CH",
    city: "Zürih",
    program: "MSc Electrical Engineering & Information Technology",
    department: "Elektrik-Elektronik Mühendisliği",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 1300,
    flag: "🇨🇭",
    deadline: "15 Aralık",
    rankings: [{ source: "QS", rank: 1, year: 2025 }],
  },
  {
    id: "imperial-ee",
    name: "Imperial College London",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc Electrical & Electronic Engineering",
    department: "Elektrik-Elektronik Mühendisliği",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 36000,
    flag: "🇬🇧",
    deadline: "Mart",
    rankings: [{ source: "QS", rank: 2, year: 2025 }],
  },
  {
    id: "epfl-ee",
    name: "EPFL – École polytechnique fédérale de Lausanne",
    country: "İsviçre",
    countryCode: "CH",
    city: "Lozan",
    program: "MSc Electrical & Electronic Engineering",
    department: "Elektrik-Elektronik Mühendisliği",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 1300,
    flag: "🇨🇭",
    deadline: "15 Aralık",
    rankings: [{ source: "QS", rank: 10, year: 2025 }],
  },
  {
    id: "tu-delft-ee",
    name: "TU Delft",
    country: "Hollanda",
    countryCode: "NL",
    city: "Delft",
    program: "MSc Electrical Engineering",
    department: "Elektrik-Elektronik Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 2209,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "kth-ee",
    name: "KTH Royal Institute of Technology",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "MSc Electrical Engineering",
    department: "Elektrik-Elektronik Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 13500,
    flag: "🇸🇪",
    deadline: "15 Ocak",
  },

  // ── Architecture / Mimarlık ──

  {
    id: "eth-zurich-arch",
    name: "ETH Zurich",
    country: "İsviçre",
    countryCode: "CH",
    city: "Zürih",
    program: "MSc Architecture",
    department: "Mimarlık",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 1300,
    flag: "🇨🇭",
    deadline: "15 Aralık",
    rankings: [{ source: "QS", rank: 1, year: 2025 }],
  },
  {
    id: "ucl-arch",
    name: "UCL – The Bartlett School of Architecture",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MArch Architecture",
    department: "Mimarlık",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 30000,
    flag: "🇬🇧",
    deadline: "Mart",
    rankings: [{ source: "QS", rank: 3, year: 2025 }],
  },
  {
    id: "tu-wien-arch",
    name: "TU Wien (Vienna University of Technology)",
    country: "Avusturya",
    countryCode: "AT",
    city: "Viyana",
    program: "MSc Architecture",
    department: "Mimarlık",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 1500,
    flag: "🇦🇹",
    deadline: "Şubat",
  },
  {
    id: "aalborg-arch",
    name: "Aalborg University",
    country: "Danimarka",
    countryCode: "DK",
    city: "Aalborg",
    program: "MSc Architecture & Design",
    department: "Mimarlık",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇰",
    deadline: "1 Mart",
  },

  // ── Economics / Ekonomi ──

  {
    id: "lse-economics",
    name: "London School of Economics and Political Science (LSE)",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc Economics",
    department: "Ekonomi",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 35000,
    flag: "🇬🇧",
    deadline: "Nisan",
    rankings: [{ source: "QS", rank: 5, year: 2025 }],
  },
  {
    id: "cambridge-economics",
    name: "University of Cambridge",
    country: "İngiltere",
    countryCode: "GB",
    city: "Cambridge",
    program: "MPhil Economics",
    department: "Ekonomi",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 35000,
    flag: "🇬🇧",
    deadline: "Aralık",
    rankings: [{ source: "QS", rank: 4, year: 2025 }],
  },
  {
    id: "oxford-economics",
    name: "University of Oxford",
    country: "İngiltere",
    countryCode: "GB",
    city: "Oxford",
    program: "MPhil Economics",
    department: "Ekonomi",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 36000,
    flag: "🇬🇧",
    deadline: "Ocak",
    rankings: [{ source: "QS", rank: 3, year: 2025 }],
  },
  {
    id: "toulouse-economics",
    name: "Toulouse School of Economics (TSE)",
    country: "Fransa",
    countryCode: "FR",
    city: "Toulouse",
    program: "MSc Economics",
    department: "Ekonomi",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 6000,
    flag: "🇫🇷",
    deadline: "Nisan",
  },
  {
    id: "stockholm-economics",
    name: "Stockholm University",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "MSc Economics",
    department: "Ekonomi",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇸🇪",
    deadline: "15 Ocak",
  },
  {
    id: "tilburg-economics",
    name: "Tilburg University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Tilburg",
    program: "MSc Economics",
    department: "Ekonomi",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
  },
  {
    id: "sorbonne-economics",
    name: "Sorbonne Université",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "MSc Economics",
    department: "Ekonomi",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 4000,
    flag: "🇫🇷",
    deadline: "Nisan",
  },
  {
    id: "zurich-economics",
    name: "University of Zurich",
    country: "İsviçre",
    countryCode: "CH",
    city: "Zürih",
    program: "MSc Economics",
    department: "Ekonomi",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 2600,
    flag: "🇨🇭",
    deadline: "Nisan",
  },

  // ── Political Science / Siyaset Bilimi ──

  {
    id: "oxford-politics",
    name: "University of Oxford",
    country: "İngiltere",
    countryCode: "GB",
    city: "Oxford",
    program: "MPhil Politics",
    department: "Siyaset Bilimi",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 36000,
    flag: "🇬🇧",
    deadline: "Ocak",
    rankings: [{ source: "QS", rank: 3, year: 2025 }],
  },
  {
    id: "leiden-politics",
    name: "Leiden University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Leiden",
    program: "MSc Political Science",
    department: "Siyaset Bilimi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "amsterdam-politics",
    name: "University of Amsterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Amsterdam",
    program: "MSc Political Science",
    department: "Siyaset Bilimi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "copenhagen-politics",
    name: "University of Copenhagen",
    country: "Danimarka",
    countryCode: "DK",
    city: "Kopenhag",
    program: "MSc Political Science",
    department: "Siyaset Bilimi",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇰",
    deadline: "1 Mart",
  },

  // ── International Relations / Uluslararası İlişkiler ──

  {
    id: "lse-ir",
    name: "London School of Economics and Political Science (LSE)",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "MSc International Relations",
    department: "Uluslararası İlişkiler",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 35000,
    flag: "🇬🇧",
    deadline: "Nisan",
    rankings: [{ source: "QS", rank: 5, year: 2025 }],
  },
  {
    id: "geneva-ir",
    name: "Graduate Institute Geneva (IHEID)",
    country: "İsviçre",
    countryCode: "CH",
    city: "Cenevre",
    program: "Master in International Affairs",
    department: "Uluslararası İlişkiler",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 8000,
    flag: "🇨🇭",
    deadline: "15 Ocak",
  },
  {
    id: "leiden-ir",
    name: "Leiden University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Den Haag",
    program: "MSc International Relations & Diplomacy",
    department: "Uluslararası İlişkiler",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },

  // ── Medicine / Tıp ──

  {
    id: "karolinska-med",
    name: "Karolinska Institute",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "MSc Biomedical Sciences",
    department: "Tıp",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 19000,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [{ source: "QS", rank: 7, year: 2025 }],
  },
  {
    id: "heidelberg-med",
    name: "Heidelberg University",
    country: "Almanya",
    countryCode: "DE",
    city: "Heidelberg",
    program: "MSc Molecular Biosciences",
    department: "Tıp",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
  },
  {
    id: "copenhagen-med",
    name: "University of Copenhagen",
    country: "Danimarka",
    countryCode: "DK",
    city: "Kopenhag",
    program: "MSc Medical Sciences",
    department: "Tıp",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇰",
    deadline: "1 Mart",
  },
  {
    id: "amsterdam-med",
    name: "University of Amsterdam",
    country: "Hollanda",
    countryCode: "NL",
    city: "Amsterdam",
    program: "MSc Biomedical Sciences",
    department: "Tıp",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },

  // ── Law / Hukuk ──

  {
    id: "oxford-law",
    name: "University of Oxford",
    country: "İngiltere",
    countryCode: "GB",
    city: "Oxford",
    program: "BCL / MJur (Master of Law)",
    department: "Hukuk",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 36000,
    flag: "🇬🇧",
    deadline: "Ocak",
    rankings: [{ source: "QS", rank: 3, year: 2025 }],
  },
  {
    id: "cambridge-law",
    name: "University of Cambridge",
    country: "İngiltere",
    countryCode: "GB",
    city: "Cambridge",
    program: "LLM Master of Law",
    department: "Hukuk",
    requiredGPA: 88,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 35000,
    flag: "🇬🇧",
    deadline: "Aralık",
    rankings: [{ source: "QS", rank: 4, year: 2025 }],
  },
  {
    id: "leiden-law",
    name: "Leiden University",
    country: "Hollanda",
    countryCode: "NL",
    city: "Leiden",
    program: "LLM European Law",
    department: "Hukuk",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 14000,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "humboldt-law",
    name: "Humboldt University of Berlin",
    country: "Almanya",
    countryCode: "DE",
    city: "Berlin",
    program: "LLM European & International Law",
    department: "Hukuk",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
  },
];
