import type { University } from "@/types";

export const universities: University[] = [
  {
    id: "tu-delft-cs",
    name: "TU Delft",
    country: "Hollanda",
    countryCode: "NL",
    city: "Delft",
    program: "Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 2209,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "tu-delft-arch",
    name: "TU Delft",
    country: "Hollanda",
    countryCode: "NL",
    city: "Delft",
    program: "Architecture",
    department: "Mimarlık",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 2209,
    flag: "🇳🇱",
    deadline: "1 Nisan",
  },
  {
    id: "groningen-business",
    name: "University of Groningen",
    country: "Hollanda",
    countryCode: "NL",
    city: "Groningen",
    program: "International Business",
    department: "İşletme",
    requiredGPA: 62,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 2209,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
  },
  {
    id: "polimi-cs",
    name: "Politecnico di Milano",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "Computer Science & Engineering",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.0",
    tuitionEUR: 3000,
    flag: "🇮🇹",
    deadline: "Şubat (erken), Nisan (geç)",
  },
  {
    id: "polimi-arch",
    name: "Politecnico di Milano",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "Architecture",
    department: "Mimarlık",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 3500,
    flag: "🇮🇹",
    deadline: "Mart",
  },
  {
    id: "bocconi-economics",
    name: "Bocconi University",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "Economics",
    department: "Ekonomi",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 14500,
    flag: "🇮🇹",
    deadline: "Ocak (erken), Nisan (geç)",
    rankings: [
      { source: "FT", rank: 6, year: 2025 },
      { source: "QS", rank: 18, year: 2025 },
    ],
  },
  {
    id: "bologna-eng",
    name: "University of Bologna",
    country: "İtalya",
    countryCode: "IT",
    city: "Bologna",
    program: "Engineering",
    department: "Mühendislik",
    requiredGPA: 65,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "5.5",
    tuitionEUR: 2900,
    flag: "🇮🇹",
    deadline: "Mayıs",
  },
  {
    id: "tum-cs",
    name: "TU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "Computer Science",
    department: "Bilgisayar Mühendisliği",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
  },
  {
    id: "tum-ee",
    name: "TU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "Electrical Engineering",
    department: "Elektrik-Elektronik Mühendisliği",
    requiredGPA: 75,
    requiredLanguage: "TestDaF",
    requiredLanguageScore: "4",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
  },
  {
    id: "lmu-business",
    name: "LMU München",
    country: "Almanya",
    countryCode: "DE",
    city: "Münih",
    program: "Business Administration",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "TestDaF",
    requiredLanguageScore: "4",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
  },
  {
    id: "rwth-aachen",
    name: "RWTH Aachen",
    country: "Almanya",
    countryCode: "DE",
    city: "Aachen",
    program: "Mechanical Engineering",
    department: "Makine Mühendisliği",
    requiredGPA: 72,
    requiredLanguage: "TestDaF",
    requiredLanguageScore: "4",
    tuitionEUR: 0,
    flag: "🇩🇪",
    deadline: "1 Mart",
  },
  {
    id: "sciences-po",
    name: "Sciences Po",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Political Science",
    department: "Siyaset Bilimi",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 14000,
    flag: "🇫🇷",
    deadline: "Şubat",
  },
  {
    id: "essec",
    name: "ESSEC Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Business Administration",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 16000,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 7, year: 2025 },
    ],
  },
  {
    id: "ie-university",
    name: "IE University",
    country: "İspanya",
    countryCode: "ES",
    city: "Madrid",
    program: "International Relations",
    department: "Uluslararası İlişkiler",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18000,
    flag: "🇪🇸",
    deadline: "Haziran",
  },
  {
    id: "kth-stockholm",
    name: "KTH Royal Institute",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "Engineering",
    department: "Mühendislik",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 13500,
    flag: "🇸🇪",
    deadline: "15 Ocak",
  },

  // ── European Business Schools (FT & QS Rankings 2025) ──

  {
    id: "insead-mim",
    name: "INSEAD",
    country: "Fransa",
    countryCode: "FR",
    city: "Fontainebleau",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 45000,
    flag: "🇫🇷",
    deadline: "Ocak (R1), Mart (R2)",
    rankings: [
      { source: "FT", rank: 1, year: 2025 },
      { source: "QS", rank: 4, year: 2025 },
    ],
  },
  {
    id: "hec-paris-mim",
    name: "HEC Paris",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 22000,
    flag: "🇫🇷",
    deadline: "Ocak (R1), Mart (R2)",
    rankings: [
      { source: "FT", rank: 2, year: 2025 },
      { source: "QS", rank: 7, year: 2025 },
    ],
  },
  {
    id: "lbs-mim",
    name: "London Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Londra",
    program: "Masters in Management",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 38000,
    flag: "🇬🇧",
    deadline: "Ocak (R1), Nisan (R2)",
    rankings: [
      { source: "FT", rank: 3, year: 2025 },
      { source: "QS", rank: 6, year: 2025 },
    ],
  },
  {
    id: "escp-mim",
    name: "ESCP Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Paris",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 19500,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 4, year: 2025 },
      { source: "QS", rank: 12, year: 2025 },
    ],
  },
  {
    id: "iese-mba",
    name: "IESE Business School",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 42000,
    flag: "🇪🇸",
    deadline: "Ekim (R1), Ocak (R2)",
    rankings: [
      { source: "FT", rank: 5, year: 2025 },
      { source: "QS", rank: 10, year: 2025 },
    ],
  },
  {
    id: "sda-bocconi-mba",
    name: "SDA Bocconi School of Management",
    country: "İtalya",
    countryCode: "IT",
    city: "Milano",
    program: "MBA / Master in Management",
    department: "İşletme",
    requiredGPA: 80,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 32000,
    flag: "🇮🇹",
    deadline: "Ocak (R1), Nisan (R2)",
    rankings: [
      { source: "FT", rank: 6, year: 2025 },
      { source: "QS", rank: 18, year: 2025 },
    ],
  },
  {
    id: "st-gallen-mim",
    name: "University of St. Gallen",
    country: "İsviçre",
    countryCode: "CH",
    city: "St. Gallen",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 3400,
    flag: "🇨🇭",
    deadline: "Mart",
    rankings: [
      { source: "FT", rank: 8, year: 2025 },
      { source: "QS", rank: 15, year: 2025 },
    ],
  },
  {
    id: "edhec-mim",
    name: "EDHEC Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Nice",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18500,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 9, year: 2025 },
    ],
  },
  {
    id: "emlyon-mim",
    name: "emlyon business school",
    country: "Fransa",
    countryCode: "FR",
    city: "Lyon",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 17500,
    flag: "🇫🇷",
    deadline: "Nisan",
    rankings: [
      { source: "FT", rank: 10, year: 2025 },
    ],
  },
  {
    id: "esade-mim",
    name: "Esade Business School",
    country: "İspanya",
    countryCode: "ES",
    city: "Barcelona",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 24000,
    flag: "🇪🇸",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 11, year: 2025 },
      { source: "QS", rank: 14, year: 2025 },
    ],
  },
  {
    id: "esmt-berlin-mim",
    name: "ESMT Berlin",
    country: "Almanya",
    countryCode: "DE",
    city: "Berlin",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 20000,
    flag: "🇩🇪",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 12, year: 2025 },
    ],
  },
  {
    id: "imd-mba",
    name: "IMD Business School",
    country: "İsviçre",
    countryCode: "CH",
    city: "Lozan",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 82,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 48000,
    flag: "🇨🇭",
    deadline: "Eylül (R1), Ocak (R2)",
    rankings: [
      { source: "FT", rank: 13, year: 2025 },
      { source: "QS", rank: 20, year: 2025 },
    ],
  },
  {
    id: "oxford-said-mba",
    name: "Oxford Saïd Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Oxford",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 42000,
    flag: "🇬🇧",
    deadline: "Eylül (R1), Ocak (R2)",
    rankings: [
      { source: "FT", rank: 14, year: 2025 },
      { source: "QS", rank: 8, year: 2025 },
    ],
  },
  {
    id: "mannheim-mim",
    name: "Mannheim Business School",
    country: "Almanya",
    countryCode: "DE",
    city: "Mannheim",
    program: "Mannheim Master in Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 1500,
    flag: "🇩🇪",
    deadline: "31 Mayıs",
    rankings: [
      { source: "FT", rank: 15, year: 2025 },
      { source: "QS", rank: 25, year: 2025 },
    ],
  },
  {
    id: "skema-mim",
    name: "SKEMA Business School",
    country: "Fransa",
    countryCode: "FR",
    city: "Lille",
    program: "Master in Management (Grande École)",
    department: "İşletme",
    requiredGPA: 70,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 16000,
    flag: "🇫🇷",
    deadline: "Mayıs",
    rankings: [
      { source: "FT", rank: 16, year: 2025 },
    ],
  },
  {
    id: "warwick-mim",
    name: "Warwick Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Coventry",
    program: "MSc Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 32000,
    flag: "🇬🇧",
    deadline: "Temmuz",
    rankings: [
      { source: "FT", rank: 18, year: 2025 },
      { source: "QS", rank: 30, year: 2025 },
    ],
  },
  {
    id: "sse-stockholm-mim",
    name: "Stockholm School of Economics",
    country: "İsveç",
    countryCode: "SE",
    city: "Stockholm",
    program: "MSc Business & Management",
    department: "İşletme",
    requiredGPA: 78,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.0",
    tuitionEUR: 0,
    flag: "🇸🇪",
    deadline: "15 Ocak",
    rankings: [
      { source: "FT", rank: 19, year: 2025 },
    ],
  },
  {
    id: "cambridge-judge-mba",
    name: "Cambridge Judge Business School",
    country: "İngiltere",
    countryCode: "GB",
    city: "Cambridge",
    program: "MBA",
    department: "İşletme",
    requiredGPA: 85,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "7.5",
    tuitionEUR: 40000,
    flag: "🇬🇧",
    deadline: "Eylül (R1), Ocak (R2)",
    rankings: [
      { source: "FT", rank: 22, year: 2025 },
      { source: "QS", rank: 5, year: 2025 },
    ],
  },
  {
    id: "vlerick-mim",
    name: "Vlerick Business School",
    country: "Belçika",
    countryCode: "BE",
    city: "Gent",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18000,
    flag: "🇧🇪",
    deadline: "Haziran",
    rankings: [
      { source: "FT", rank: 25, year: 2025 },
    ],
  },
  {
    id: "rsm-erasmus-mim",
    name: "Rotterdam School of Management (Erasmus)",
    country: "Hollanda",
    countryCode: "NL",
    city: "Rotterdam",
    program: "MSc International Management",
    department: "İşletme",
    requiredGPA: 75,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 18500,
    flag: "🇳🇱",
    deadline: "1 Mayıs",
    rankings: [
      { source: "FT", rank: 33, year: 2025 },
      { source: "QS", rank: 35, year: 2025 },
    ],
  },
  {
    id: "frankfurt-school-mim",
    name: "Frankfurt School of Finance & Management",
    country: "Almanya",
    countryCode: "DE",
    city: "Frankfurt",
    program: "Master in Management",
    department: "İşletme",
    requiredGPA: 72,
    requiredLanguage: "IELTS",
    requiredLanguageScore: "6.5",
    tuitionEUR: 19500,
    flag: "🇩🇪",
    deadline: "15 Temmuz",
    rankings: [
      { source: "FT", rank: 32, year: 2025 },
    ],
  },
];
